### ISSUE TITLE
[Question/Bug] How does vehicle repair work

### ISSUE THREAD

**Issue by AspectSk** [P3pp3rF1y/AncientWarfare2#1020]
I remember reading somewhere that siege engineers repair their vehicles when no target is seen but i am not sure about that, as they dont do it. When i had a damaged cannon the engineer just sat on top of it and if i put a second engineer he just stood because he had no vehicle in sight, so i am not sure if you somehow changed it but i think its just a bug. I also think that there should be a way of repairing vehicles manually because just relying on engineers is kinda unreliable

**Comment by ThatPolishKid99** [comment]
There is no way to repair vehicles. We plan to add both manual and engineer ways in the future. The only up to date source of information on this mod is in the in game manual, the Treatise on Principles of Ruling, or on our discord. Also, please join that discord for easier communication and so that we can keep the issue tracker clean.
