### ISSUE TITLE
How to disable spawning of structures in Twilight Forest?

### ISSUE THREAD

**Issue by itstoasttime** [P3pp3rF1y/AncientWarfare2#1031]
The structures spawn in the twilight forest, but how do I only set it so it only spawns in the regular world?

**Comment by ThatPolishKid99** [comment]
The only time I saw AW structures spawn in the Twilight Forest was back in 1.7.10, and if I’m not mistaken, that was fixed in 1.12.
If this is from the 1.12 version, please let us know and we can look into it, we would need the AW mod version and the forge version you are running, along with your mod list 
If this is for 1.7.10, then I’m sorry about development has ceased for that version and it is discontinued, so no fixes will be coming. If you’re running 1.7, please close the issue when you get this
