### ISSUE TITLE
Spartan Weaponry/Shields Integration 

### ISSUE THREAD

**Issue by MokahTGS** [P3pp3rF1y/AncientWarfare2#1039]
Any chance we can see Spartan Weaponry be integrated into this mod so that NPCs use those weapons instead of the default ones?  Currently the shields dropped are useable as normal shields and it would be great to kill a bandit and loot a dagger or an orc and loot a great axe.

**Comment by ThatPolishKid99** [comment]
We plan to add support for player owned NPCs to use Spartan Weaponry, for the ones they can’t already use. However, for faction NPCs, I am not sure if we will add support for Spartan Weaponry or any other weapons mods because we don’t want to create an unnecessary dependency on another mod. That may change in the future, and I’ll add it to our suggestion list in the wiki. Please join our discord for quicker responses.

**Comment by MokahTGS** [comment]
I was thinking more of and option switch either in the configs or in the mod itself that detects if SW is present and then switches if it is.  That way there isn't the problem of the dependencies that you mention.  Several other mods do this and it's a really nice QoL feature on servers.
