### ISSUE TITLE
Farms can't place blocks in protected area

### ISSUE THREAD

**Issue by Hhrunting** [P3pp3rF1y/AncientWarfare2#1045]
Hello i'm currently running a catserver 1.12.2 FORGE + spigot Server, and everything was going good until I realized that machines from AW2 (i.e 'crop farm, ect') cannot place blocks inside of protected claims from plugins like World Guard, or Grief Prevention! I did notice in the configs you have the line: 
B:fire_block_break_events=boolean
Which does allow them to bypass breaking blocks when false, but is it possible for you to add a bypass on the .BlockPlaceEvent as well?

**Comment by ThatPolishKid99** [comment]
Hi, this issue would be on the land protection plugin or mod to allow for giving permission to the AW fake player to conduct its actions. Many mods and even plugins use this system, so I would expect this to be a feature somewhere. I am not familiar with those plugins, so you’ll need to ask them. I will leave this issue up so that if you find a solution, you can let us know, and so that if we discover something we can do to fix it on our end, we’ll refer to this

**Comment by Hhrunting** [comment]
ok thank you for clearing that up! I was curious about the Fake Player situation, but couldn't figure out exactly what ENUM/id I was looking for to add to the line in configs! I had a stroll through the en_US lang files but there is quite a bit there, and I also did some google searching but no luck! This plugin does in fact have the option to allow players/fake players to bypass all claims! what exactly is the Fake Player name that I need?

**Comment by Hhrunting** [comment]
The issue has been resolved the name of the Fake Player needed for Ancient Warfare 2 Automation is AncientWarfareFakePlayer
