### ISSUE TITLE
Items are swapping but I can't see them... 

### ISSUE THREAD

**Issue by sakurasuraisu** [P3pp3rF1y/AncientWarfare2#1050]
Such as, when I press ''F'' to swap items, they are not visible for me :(   I have a modpack for my own use and When I add this mod into the Minecraft, this happens... I can't see the items. When I remove this mod, my items are visible again. Please, fix this problem... This mod is WONDERFUL! I very love this mod. Please fix this....

**Comment by P3pp3rF1y** [comment]
I have no idea what your issue is, like literally you can't see items in your inventory? I don't know of any part of the mod that could affect all items like this, the most it can affect are its own items. And this is also the first time I am hearing about anything like this in a modpack where AW is in and we definitely have a lot of players playing with the mod in many different modpacks.
So we will definitely need more information on this (what other mods, especially ones that affect any rendering) and you should probably try removing other mods as well to see if this is perhaps just something from another mod that manifests when AW is added.

**Comment by P3pp3rF1y** [comment]
Closing this as it's likely not AW issue at all and we haven't got anymore details on environment, how to recreate.

**Comment by sakurasuraisu** [comment]
Hello, Thank you so much for your help. AW have not like this issue. I
fixed this problem with randomly... Anyways, when I have problem, I'll send
them again. Thanks for all your help! :)
