### ISSUE TITLE
Vanilla and MCA villages not generate

### ISSUE THREAD

**Issue by sigfrido13** [P3pp3rF1y/AncientWarfare2#1054]
Hi, 
I have install AW2 in server and when worlds creates no vanilla, MCA villages generate in overwolrd, others villages of AW2 don't generate too.
I open structures config fila and in villages generatio section is empty, how activate other villages generate.

Thanks

**Comment by MohawkyMagoo** [comment]
AW2 does not touch or interfere with vanilla villages in any way. If you are not seeing either vanilla, MCA or AW structures then thats a server problem, nothing to do with AW.

**Comment by sigfrido13** [comment]
Thanks for the quick response, I have two more problems with AW2,
Capture 1:
![capture1](https://user-images.githubusercontent.com/57373458/68202530-33d85800-ffc4-11e9-9b3e-33eeca464c36.GIF)
What does this error mean?
Capture 2:
![capture2](https://user-images.githubusercontent.com/57373458/68202543-3d61c000-ffc4-11e9-9835-b29cab0be02c.GIF)
How can I enable the generation of these structures in survival.

Thank you very much

**Comment by P3pp3rF1y** [comment]
Those first errors don't mean anything really, I will need to prevent them from showing in the log, because the files it complains about are part of manual and thus client side only and because of that they don't have a parser defined on server. 

you can make structures survival by marking them as such in their templates.

And please join our discord for questions like these, you will get response much faster and we can keep this issue tracker for real issues.
