### ISSUE TITLE
Structure Builder Crash

### ISSUE THREAD

**Issue by Nidero** [P3pp3rF1y/AncientWarfare2#1069]
This issue occurs when reskillable is installed with ancientwarfare

Right-clicking or left-clicking Structure Builder after placing Structure Builder will crash

VanillaFix points the crash cause to ancientwarfare, so I first come here to submit issues

Please let me know if it is not a problem caused by ancientwarfare and I will report this issue to reskillable developers

This is the content of the crash report: https://paste.ubuntu.com/p/BNFPPNDNbF/

**Comment by P3pp3rF1y** [comment]
This is because reskillable calls writeToNBT on tile entity client side. I could potentially make sure that this  doesn't crash for structure builder, but given that the method is supposed to be called on server side only I would imagine there will many other cases of blocks where this will crash because mods are not ready for server side only method to be called on client.
