### ISSUE TITLE
AW2 does not respect Peaceful mode

### ISSUE THREAD

**Issue by trevorjd** [P3pp3rF1y/AncientWarfare2#1088]
My game is currently set to Peaceful but the Norska NPCs around this tower are still spawning when I get close to the custom spawner blocks and attacking me. And they do not disappear when toggling from normal to peaceful.

ancientwarfare-1.12.2-2.7.0.772

**Comment by WinDanesz** [comment]
NPCs spawn in survival mode regardless of the difficulty, this won't be changed, because not all NPCs are hostile and their standing against players can vary. E.g. PlayerA might be hostile to the Noggs (because he killed a lot of them), while PlayerB is friendly to them -> no way to decide if they are hostile or friendly mobs in a multiplayer game, and we won't change game mechanics between single and multiplayer. Also AW is not a Peaceful mode enhancement mod, but a dungeon/exploration/warfare themed mod.
They can't hurt you in Peaceful.

**Comment by trevorjd** [comment]
Heyo, thanks for the reply.   Your choices are fine by me, I was just mentioning what seemed to be a bug.

> They can't hurt you in Peaceful.

Might want to double check that. Unfortunately I'm away from home at the moment and don't have my gaming PC here but I'm positive that I was taking damage when in peaceful. Or you might not! I'll leave it with you guys. Cheers.

**Comment by LostQuasar** [comment]
They definitely still hurt you in peaceful, I'd appreciate this being resolved
