### ISSUE TITLE
Dragon fire makes gates invisible (indev) 

### ISSUE THREAD

**Issue by Techster284** [P3pp3rF1y/AncientWarfare2#1138]
so in addition to the tamed mob issue that I brought up in suggestions 2 days ago about npc's not attacking your tamed mobs. I found that when Iron Gates for example are it by dragon fire they turn invisible but they still work you just can't see them also charred blocks form at the place were the gate is (although it doesn't get destroyed) also sorry for my bad english it isn't really widely used were I come from.

**Comment by xxgp77xx** [comment]
This also was the case for me when trying to use tnt to destroy a gate

**Comment by WinDanesz** [comment]
If you say dragon, I am going to assume its the vanilla end dragon. I'm fairly sure you were talking about the Ice and Fire mod's dragon, but don't assume that we can figure out what you have in your mind, be more specific. 
The issue is because I&F dragonfire messes up all kind of blocks, the AW invisible gate "proxy blocks" too, there is nothing we can do from our side. You have to blacklist this block from dragonfire so dragons cant burn it, there is a blacklistedBreakBlocks config in I&F, the block is "ancientwarfarestructure:gate_proxy".

Regarding xxgp77xx's issue, we'll look into that TNT problem, that is a different issue.
