### ISSUE TITLE
Need a null check 

### ISSUE THREAD

**Issue by jizzy123** [P3pp3rF1y/AncientWarfare2#1141]
https://github.com/P3pp3rF1y/AncientWarfare2/blob/13419048a4cea745547bbee883ad461c4863e4e5/src/main/java/net/shadowmage/ancientwarfare/vehicle/input/VehicleCallback.java#L20

A null check is needed. It is causing problems with other mods.

**Comment by P3pp3rF1y** [comment]
You will need to provide more info on this. Why is the null check needed? If it's because in your instance ridingentity could be null or not of VehicleBase type then that means some mod messes up with keybinds because the vehicle ones are set to trigger only if player is riding a vehicle. 
if you have a crash log please add it here so that we can take a look
