### ISSUE TITLE
Bug report, "Crashing the game I'm so good."

### ISSUE THREAD

**Issue by notasuka** [P3pp3rF1y/AncientWarfare2#1175]
## Context Environment
Minecraft version: 1.12.2

Ancient Warfare 2 version: 2.7.0.772

Minecraft Forge version: 14.23.5.2847

Crash log: https://pastebin.com/raw/PNsJ32ju

## Current Behavior
Not expecting riding entity to be nullable?

**Comment by ThatPolishKid99** [comment]
Hi, can we get more information that you were supposed to fill in the bug template for, namely, what you were doing when this crash occurred, and can it be replicated in just an AW environment.

**Comment by P3pp3rF1y** [comment]
The only thing you seem to have found is that you have a mod in your modpack that messes with other mods keybinds, specifically with key conflict context of those, because in your case vehicle keybinds fire despite there being no vehicle around. And the vehicle keybinds key conlict context has a condition included that they can only fire if the player is riding a vehicle. There's no way around that unless something messes with it. 
And given that this issue report doesn't seem to have much else in terms of additional info to recreate we can do just one thing and that is close it.
