### ISSUE TITLE
The courier doesn't take any item from the farms

### ISSUE THREAD

**Issue by ILAIGG** [P3pp3rF1y/AncientWarfare2#1182]
I don't know if I just don't know how the mod works or why, but the courtesan doesn't take any item from the farms (fruit, crop, etc)
I was already around two hours trying to solve it (making him take the item from another side, reading the wiki, watching tutorials, etc.), but I can't find any solution.
PS: he yes, take the items from the chests

**Comment by ThatPolishKid99** [comment]
If you read the in game manual or the wiki on this Github thoroughly, I think you would have identified the issue, which is most likely due to improper side assignments in the routing order. 
This issue tracker is for identified bugs and crashes, please join our discord, linked on our Curseforge page and in a token on the readme on this Github, to ask more generic questions like this, we would be happy to help you there
