### ISSUE TITLE
Game Crashing On Startup

### ISSUE THREAD

**Issue by DrAmigo** [P3pp3rF1y/AncientWarfare2#1278]
Minecraft version: 1.12.2

Ancient Warfare 2 version: 2.7.0.1038

Minecraft Forge version: 1.12.2 - 14.23.5.2855

Link to your crash log (if the game crashes): 
[crash-2021-05-30_00.26.57-client.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/6565698/crash-2021-05-30_00.26.57-client.txt)

If you are using a modpack, link to the pack: While im not using a pack, I do have other mods installed

The mods are:

- Blood Magic
- Chisels and bits
- Code Chicken Lib
- Guide API
- Industrial Craft
- Iron Backpacks
- Iron Chest
- Journey Map
- Mantle
- Pan's HarvestCraft
- Tinker's Construct
- Twilight Forest

## Expected Behavior

Not crash on startup
## Current Behavior

It crashes on startup
## Steps to Reproduce
1.Have all the mods I am currently using (At this point in time all of the mods i'm using are in their most recent version for 1.12)
2. Start
3.
4.

## Possible Solution

Different mods?

**Comment by SyndicMohawky** [comment]
You have nowhere near enough RAM (memory) assigned for modded minecraft. From your log: Memory: 294034872 bytes (280 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)  

2gb is not enough to run AW2   you need minimum 4gb  or recommended 6gb.   Your game is failing because AW2 doesnt have the memory resources needed to generate structures.

**Comment by DrAmigo** [comment]
I have a feeling you're a ram salesman trying to sell me RAM

**Comment by WinDanesz** [comment]
Yes he is. Buy and install that RAM.
