### ISSUE TITLE
aw2 crashes everytime i load minecraft with it

### ISSUE THREAD

**Issue by castleofhell** [P3pp3rF1y/AncientWarfare2#1343]
my forge version is 1.12.2 14.23.5.2855 and im running nothing else but aw2 and code chicken lib

**Comment by ThatPolishKid99** [comment]
Next time, you must use the issue tracker template, in order to provide the information we needs. Like the crash report. 
I am going to recommend looking into how much RAM you have assigned to Minecraft, you need at least 4 GBs assigned to run AW, recommended at least 6 GBs. Also, I would downgrade Forge to version ending in .2854.
Finally, I would join our discord server to receive quicker support and avoid cluttering the issue tracker. 
I am going to close this issue, you should join our Discord where we can more easily support you, if nothing above helps you. We can handle it from there
