### ISSUE TITLE
Whats up with banning people on discord for asking questions?

### ISSUE THREAD

**Issue by SafeExtract** [P3pp3rF1y/AncientWarfare2#1377]
Needed help for my modpack and got banned for asking stuff around, what kind of team is that?

**Comment by sissyboyheyfray** [comment]
Not surprising, the team behind this mod tends to just ban people instead of addressing simple issues that should have been fixed years ago.

Basically, the mod is abandonware. You can add all the pretty castles you want, but if the mod is a broken turd, and if you ban users for asking simple questions, you're basically destroying any little bit of community you have.

**Comment by ThatPolishKid99** [comment]
> Needed help for my modpack and got banned for asking stuff around, what kind of team is that?

You were likely banned for not reading the rules and the FAQ which articulate what we need in order to help you. You can DM me on discord if you believe this was in error. As you can see by the other comment, we get a lot of trolls and other asshats that don’t have lives, instead choosing to harass people who make Minecraft mods. I apologize for the inconvenience.

That being said, this issue tracker is for bugs, not questions.

**Comment by sissyboyheyfray** [comment]
> > Needed help for my modpack and got banned for asking stuff around, what kind of team is that?
> 
> You were likely banned for not reading the rules and the FAQ which articulate what we need in order to help you. You can DM me on discord if you believe this was in error. As you can see by the other comment, we get a lot of trolls and other asshats that don’t have lives, instead choosing to harass people who make Minecraft mods. I apologize for the inconvenience.
> 
> That being said, this issue tracker is for bugs, not questions.

I kid you not, noone else has this issue but you. When you act the way you act, you invite people to brigade you, then you get more and more paranoid as a result of that brigading, resulting in you creating an echo chamber where if anyone criticizes you they get banned, and people get frustrated and the cycle repeats over and over again. That's why people hate you.

**Comment by SafeExtract** [comment]
No, I saw several people reporting they got banned for no reason, even banned for trying to help other people. What a joke, I'm not dming anyone. 

Asshats devs that ban people who needs help with the mod? Why even have a discord then?
