### ISSUE TITLE
AncientWarfareStructures.cfg missing config option from earlier versions (ancientwarfare-1.12.2-2.7.0.1038.jar)

### ISSUE THREAD

**Issue by darchitectlp** [P3pp3rF1y/AncientWarfare2#1383]
## Context Environment
Minecraft version: 1.12.2

Ancient Warfare 2 version:
ancientwarfare-1.12.2-2.7.0.1038.jar

Minecraft Forge version:
14.23.5.2858

Link to your crash log (if the game crashes):

If you are using a modpack, link to the pack: 
https://www.curseforge.com/minecraft/modpacks/ancient-warfare-horizons

## Expected Behavior
Was scanning the internet trying to figure out how to reduce structure spawns. Could not find config options mentioned in other posts (eg: "I:max_cluster_value=500" and "I:validation_cluster_value_search_radius=16"). So I deleted AncientWarfareStructures.cfg so the mod would generate a new cfg file, but it seems many options are missing, or are out of order. I did a quick screenshot of a couple of modpacks' cfg files from older, un-updated versions of AW2.

![Screen Shot 2022-03-21 at 3 01 34 PM](https://user-images.githubusercontent.com/36024900/159349549-79ac8f14-2d28-4f83-ae78-2376f5333912.png)

## Current Behavior
Config doesn't seem to work regarding structure rarity... even after I set "D:random_generation_chance=0.035", and create a new world with the same seed, I get a similar amount of the same structures spawning near the same places and using the same buildings as when I used the default "D:random_generation_chance=0.07500000298023224". However, when I reduced the "D:town_generation_chance=0.125" to 0.09, it DID seem to work on the towns.

## Steps to Reproduce
Boot it up and run; try changing the structure rarity.

Couple side notes while I'm here (and I know I should probably open bug reports for these. I apologize.): I unzipped the jar files to look through the structure templates and realized a great many of them have no biomesoplenty tags. I think a lot of the structures never get seen since vanilla biomes get swallowed up by BOP. I'd be more than happy to help update the aws/awt with more biome tags. That brings me to my last point: is there any chance AW2 will allow for using Forge's biome dictionary instead of specifying a certain biome? Just a hope for the future.

Thank you for such an amazing mod. I hope you have the bandwidth to keep working on it; it's wonderful! Especially the integration with other mods!!!

**Comment by SyndicMohawky** [comment]
From our discord FAQ:

Q:  I want to make structures spawn MORE or LESS often, have changed config setting but it doesn’t work! Why?
A:  It doesn’t work because there is NO CONFIG SETTING THAT CAN DO THAT! 

AW2 structure generation is very complex and is governed by a number of factors SOME OF WHICH CANNOT BE ACCESSED BY THE USER

1:     Normal world gen of AW2 structures is handled separately from AW2 City generation. 
2:    Tribes and Nations structures are set to cluster densely in their “home biomes” this is not user controllable. Tribe or Nations spawning is controlled by the AW Territory system WHICH IS NOT ACCESSIBLE TO USERS.
More info here: https://discord.com/channels/440863937777369088/496320171321982976/801429977924632598
3:    How a structure spawns, how it is weighted and where it spawns is controlled by the individual structures template NOT THE GENERAL CONFIGS. To change these you would have to make changes to over 2,000 files, and resave them. 
4:    The general config settings are general guidelines that the rest of the unseen system plugs into. YOU MESS WITH THE GENERAL CONFIG SETTINGS AT YOUR OWN PERIL – because what you are generally doing by changing those is mostly disabling huge numbers of structures from spawning that you will never see or experience – not just making their generation rarer, or more frequent.
See here for advice on how to create more open space in your worlds: https://discord.com/channels/440863937777369088/496320171321982976/749659181535068220

**Comment by SyndicMohawky** [comment]
And thanks, but the structures are set to spawn in the biomes we want them in.  And no, biome dictionary is too crude a tool to apply.

**Comment by SyndicMohawky** [comment]
Also, the 1038 structure spawning system has been completely revamped, and over a thousand new structures added for the next update, so any feedback on that old structure pack is irrelevant and meaningless to us now, as all of those old structures have been completely revised.

You would gain more info from our discord. Github is not the place for this.

**Comment by SyndicMohawky** [comment]
And, feedback from most BOP users wanted a high proportion of their biomes structure free - this is deliberate.

**Comment by darchitectlp** [comment]
Thanks for your reply! I'm assuming you're the mohawk who did all the work on the structure files? If so, thanks! Any chance some of that discord data can be moved into the wiki here? At least just letting people know they can't change that stuff. (As a side note, I really worry about so much of the info shared of discord being inaccessible to search engines.)

Do you know why the config options disappeared from the latest build on curse? Or why the config file is missing the previously mentioned options? I just want to make sure that the config is actually working the way it was intended.

Oh you just posted a new reply! Ok, no worries! One last question: is the update being worked on for 1.12 or another version? Regardless, thanks for your response and your work!

**Comment by SyndicMohawky** [comment]
The final update will be in 1.12 - there are no current plans to update to newer mnecraft versions after that. 

Not sure what you mean on "missing config options" the configs are exactly as they should be?

**Comment by darchitectlp** [comment]
Glad to hear you're sticking to 1.12. I was worried about the cfg being messed up because it was missing options that existed in previous versions (if you look at the side-by-side image I posted, you can see). But it sounds like all that was intentional, anyway.
