### ISSUE TITLE
Drafting Table GUI wonkey

### ISSUE THREAD

**Issue by Nozgo** [P3pp3rF1y/AncientWarfare2#14]
When you click the drafting table its layout is wonkey and just says 
guistrings.structure.select_structure
   guistrings.structure.no_selection
   guistrings.output
   guistrings.input
![javaw 2014-06-17 18-46-25-65](https://cloud.githubusercontent.com/assets/3727863/3308336/9a3e5a5c-f67b-11e3-9214-8b5e5ce7395b.png)

**Comment by shadowmage45** [comment]
That is indeed a bit wonky.

This appears to be two separate issues:
1.)  Missing a few translation keys for the strings used in the GUI / hardcoded references rather than going through the translator.  That one is easy to fix.
2.)  Something has messed up the initial lighting settings for GUI rendering (which is causing the black background).  I'll look into manually setting the necessary openGL parameters prior to any gui rendering.  That particular issue is likely caused by a mod, AW or otherwise, not properly resetting any openGL attributes that they changed during some rendering routine -- more than likely something doing world rendering or overlays (nei, minimaps).

**Comment by Nozgo** [comment]
I have NEI, Voxels Minimap, and optifine, just an fyi. Odd thing is all the other GUI's are fine.
