### ISSUE TITLE
Ancient Warfare Vehicles.

### ISSUE THREAD

**Issue by Durixiiik** [P3pp3rF1y/AncientWarfare2#1432]
What can i do when i need vehicles in version 1.7.10. Is somewhere version with vehicles?

**Comment by ThatPolishKid99** [comment]
Please do not open new issue when the old one was closed. You can still comment on closed issues.
To clarify the last issue a bit, there is no version of 1.7.10 AW that had vehicles. It simply never existed, and since the 1.7.10 version is no longer supported, there never will be. I am sorry if this is a major issue for you, but the 1.12 version does have vehicles and is supported
