### ISSUE TITLE
Expand default structure pack with additional world gen

### ISSUE THREAD

**Issue by shadowmage45** [P3pp3rF1y/AncientWarfare2#167]
Add at least one template of each additional validation type:

Water (boats)
Underwater (sunken temple)
Island (mid-ocean pirate fortress?)
Air (sky temple?)
Underground (dungeon)
Harbor (uhh...maybe not this one...)

**Comment by Dulciphi** [comment]
An optional Sky temple? Cool ;) 
Mid-ocean pirate fortress, yes please! That would be unreal. I can understand the trouble with the Harbour - I can imagine it'd be impossible to stop them generating in a pond. Awesome if it could be done, but since it can't be done yet, pirate island fortress mid-ocean would be great. Then, if players want, they can fiddle around with building it on shores with the survival structure builder themselves. 

Sunken temple, definitely ..maybe. The only Q I have is what baddies you'd put in it. It would be a must for a mod structure pack. Or wait. Would it be one of your clever trap designs? Maybe combine with zombie spawners? (undead pirates). 

I'm not too keen on boats myself (If by boats you mean built, static boats). That's just my taste though and I could always disable them. The sails just never look right to me with blocks of wool. Especially next to real boats. Wait.. Unless you meant randomly spawning your ships. But..?
