### ISSUE TITLE
Farmers not working with wool farm

### ISSUE THREAD

**Issue by MinecraftsBestGuy** [P3pp3rF1y/AncientWarfare2#171]
Recently I have found a bug where farmers won't do anything with a wool farm. I think having a cow farm next to it might of been a problem. Fix?

**Comment by MinecraftsBestGuy** [comment]
I couldn't get ahold of the mod author, so can someone tell someone about the issue please?

**Comment by MinecraftsBestGuy** [comment]
being near cow farm not a problem, i was using a novice farmer though

**Comment by Dulciphi** [comment]
Version 1.6.4?

**Comment by shadowmage45** [comment]
AW2 has neither wool farms nor novice farmers.  Those are both from AW1.

I am no longer offering public support for AW1.  You are free to ask on the forums though.  (As it has been -over- a year since I have played with it, and months since I looked at the source code, I'm probably not the best to answer those questions anymore anyhow)

**Comment by MinecraftsBestGuy** [comment]
thank you
