### ISSUE TITLE
New Idea - Advenced Warfare

### ISSUE THREAD

**Issue by sarloving** [P3pp3rF1y/AncientWarfare2#172]
Hello. First sorry for my english. 
Second. I think this is a very great mod and the creator can make more than catapults, ships, helicopters etc. I know this is ANCIENT but i think this mod need more than have now.
Ideas:
Random villages with some types like viking and arabic etc. and a new block where the player can manage the reputation with the villages (alliance, war) where see every resources and an optimized map where can see their village borders. (The player can improve the borders with good reputation with prestige from every npc kill or with economical points). And in this block the player need to research ages to get more technologies from the stone age to the industrial age and this last age can give more/better vechiles like better airplanes or tanks or better artillery.
If the player create a village in the village need womens and the people can grow and the kids grow up. The player need to make the recuiting table and make officer npc to recuit npcs to soldiers and train them. 
And better command like the npcs can use the helicopters or airplanes to attack and a map item where the player can give orders to their battle groups. Yeah i think its very hard but its only an idea :)

**Comment by Dulciphi** [comment]
I do like the idea of child NPCs instead of essentially crafting them out of gold, some pork chops and an apple - but then where do the original NPCs come from? From the existing default structures (there's your random villages - and they have different factions like viking and pirate, etc). Currently, the way to improve your reputation with the different factions is via trading with the trader NPCs.

Extending on the idea of NPC children - I also like the idea of having to recruit them and then train them into jobs or roles, and have them level up from there. I also like the idea of having extendable borders that could perhaps increase your maximum population limit - but all of this is for way down the track (if at all) after Shadowmage has completed the vehicles module. Certainly I've dreamed of  an AncientWarfare addon that adds the NPC breeding and recruiting mechanics among other things. 

You can read more about the existing features in the [Instruction Manual](https://github.com/shadowmage45/AncientWarfare2/releases/download/2.3.75-beta-MC1710-RC1/instruction_manual_2.3.75-beta.pdf) though it's only in English at the moment.

**Comment by shadowmage45** [comment]
Advanced vehicles -- perhaps later, after the initial vehicles are added back in :)

Expanding villages, borders, etc... not likely.  I have addressed these concerns before in the dev-conversation thread;  There are too many exploitability and performance issues to work through to likely ever see this in AW.  Trying to track 'population' is, well, impossible with the way MC manages chunks -- you have no guarantee that the entire settlement would every be loaded at the same time, and thus no way to every count the full population reliably.

Recruiting of NPCs;  While I will agree that recruiting them from thin air is a bit...unbelievable, I have not been able to find a suitable replacement mechanic that is simple to use (from a player perspective) and simple to implement and maintain (from a coding perspective).  (See above for just one of the problems encountered)

**Comment by sarloving** [comment]
Yeah i understand. I see the new patches it's a very great mod :) 
I have only 2 problems. 
I can't see the AW recipes withouth NEI and the NPC's house location.  But i like the new bandits :D

**Comment by Dulciphi** [comment]
Yeah NEI is pretty essential. I can't even remember a lot of the basic vanilla minecraft recipes without NEI ;)

There are plenty more structures coming soon but don't forget you can still make your own Player owned NPCs and build any kind of house you like for them. You could even get your NPCs to help you build a whole town.
