### ISSUE TITLE
Highly enchanted tools upgrade not working

### ISSUE THREAD

**Issue by Devostar** [P3pp3rF1y/AncientWarfare2#190]
So I finally managed to get me a fortune II book.
I stopped my quarry so I could use the highly enchanted tools to get as many diamonds as possible.
I used the fortune II book in the recipe as shown (1 book with a row of 3 iron under it).

And I got a Lightly enchanted tools book.

I used Minefactory Reloaded to get the book (auto-enchanter on golden pickaxe and the auto-disenchanter to turn the fortune II enchantment into a book)

**Comment by shadowmage45** [comment]
Hmm.. this is a bit of a strange issue.

Apparently the recipe is not properly respecting the enchantment on the book, and will allow -any- enchanted book to be used, and the result will be the lightly enchanted tools upgrade.

Will be changing this recipe around, so that -any- enchanted book gets you light-enchanted upgrade, while 2x any book gives highly enchanted upgrade.

I -really- wanted to require fortune for those, but apparently the MC recipe system cannot handle that sub-data for recipe matching/validation (and/or someone added enchanted books to the ore-dictionary....)
