### ISSUE TITLE
Crafting

### ISSUE THREAD

**Issue by madshammy** [P3pp3rF1y/AncientWarfare2#194]
When ever i try to craft an item I get a hard crash to desktop.  This particular one is from trying to craft the animal farm.  I got the Oak Planks in, but as soon as i put the Iron Sword in I got the crash.

https://gist.github.com/anonymous/5688b1ad3f37895eb1a5

**Comment by shadowmage45** [comment]
This is caused by an improper NEI plugin:

java.lang.ArrayIndexOutOfBoundsException: 0
at ru.itaros.chemlab.addon.nei.MachineCrafterRecipes.getRecipeHandler(MachineCrafterRecipes.java:152)
at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20) 

Whatever is adding 'ru.itaros.chemlab.addon' is responsible for the crash.  They are likely not checking the recipe type properly when determining whether or not to use their NEI handler, as there is no reason for any other mods' NEI addon to be handling AW recipes.
