### ISSUE TITLE
NPCs/Gates/Vehicles from AW1 (1.6.4) templates not spawning

### ISSUE THREAD

**Issue by Nozgo** [P3pp3rF1y/AncientWarfare2#25]
Any buildings both world gen and placed do not have any castle gates, drawbridges or retracting bridges that should come with them.

**Comment by Nozgo** [comment]
Also, no npc's are spawning with structures either. Did not want to create another issue for this in case you are already tracking it, or if its a non-issue that I am just doing something wrong.

**Comment by shadowmage45** [comment]
Yep, this is a non-issue.  I will probably leave this as an open issue for a bit so others can track it though -- thanks for reporting.

You are using an outdated (1.6.4) structure pack and/or templates.  That is why there is a whole ton of error message-spew in the console when you load with the old packs.  

Structure packs will need to be updated.  Pack makers knew ahead-of-time that gates/npcs/vehicles would become invalidated and that packs would have to be updated.  There were too many internal changes (and external changes...) in the entities' code to allow them to be compatible across releases.

Essentially, the old templates should load well enough that they can be instant-built, touched up, and rescanned by their authors, and are not meant to be transferred wholesale between MC versions (at least not this MC update -- far too many changes in the id/name handling for that=)

The default structure pack will probably be updated a bit later in the testing period -- need to make sure the structure generation system is -working- and that it can handle all of the gates / npcs / vanilla entities properly before I will be spending any time creating templates.

**Comment by Nozgo** [comment]
Will structure packs be player supplied, or will you have a standard one? I have yet to mess with the scanner so I suppose I should do so. I will look into how to add npc's to a scanned structure.

**Comment by shadowmage45** [comment]
"The default structure pack will probably be updated a bit later in the testing period -- need to make sure the structure generation system is -working- and that it can handle all of the gates / npcs / vanilla entities properly before I will be spending any time creating templates."

Structures are mostly player supplied -- the entire system is there so that -you- can setup your world generation to be how you would like it to be.

The published structure packs are provided for users that don't care/want to take the time to set things up for themselves. Right now, there are no published packs for the 1.7 test versions -- its only been in testing for a couple of days...give it a bit and let thing stabilize, and I'm sure that Mohawky will update his pack / publish his 2nd/3rd packs he's been working on :)

Adding NPCs into scanned structures should be as simple as scanning the structure while the NPCs are in it :)

**Comment by P3pp3rF1y** [comment]
Closing as this actually is part of both 1.7.10 and 1.12.2 version
