### ISSUE TITLE
Future possibilities?

### ISSUE THREAD

**Issue by SkiesFallSunder** [P3pp3rF1y/AncientWarfare2#280]
I greatly enjoy the thought of running my own civilization, however I run 100+ mods and the majority of them add in items, mobs and all that goodie goodie stuff. I'm not entirely sure if there's already a way to do so, but perhaps you could add in an item, or modify the Command Baton to Add/Remove entities to attack.

Companion NPC's, Almost like a tamed mob they'll follow you around on your adventure.
Another interesting role could be a guardian/champion/brute. One that's a tad bit stronger than the rest with more of a built figure. I'm not sure if this is far fetched but Angelic soldiers.

A way to mark your civilization, E.G the limits of it for invasion events. 

These are all just thoughts. I'm looking forward to future updates.

-SkiesFallSunder

**Comment by Dulciphi** [comment]
Seems you're thinking along the same lines as I am. 

There is a Command Baton and AncientWarfareNpcTargeting.cfg lets you configure the entities that will be considered hostile, etc - but what really interests me is the way to mark the civilization, eg. the limits for invasion events.

The trouble in the past, as expressed by Shadowmage, was that Minecraft provides no way to recognise a structure (ie. a wall as opposed to just a few blocks or even terrain. I've been thinking about it for ages and the idea I'd love to implement/I'm trying to implement is to have raids spawn a set distance from a town hall. This would require a few things:
1. the NPCs couldn't be fed from chests or other inventories. They would _need_ a town hall.
2. the raiding parties would need the ability to breach walls (I'm currently working with Father Toast's Apocalypse mod for this).
3. the raiding parties would need an AI similar to zombies in that they can have primary and secondary targets. The primary target would be the town hall block - unless they themselves are hit.
4. the raiders need griefing AI (I'm using Father Toast's SpecialAI to experiment for now, getting them to target the town hall block)
5. the problem with this is that it sets a limit on how far the walls can be from a town hall block. If you build your wall too far out, raiders will spawn within the walls. Boundaries could be extended either by using additional town hall blocks or by upgrading the town hall. My preferred method would be additional town hall blocks.
6. town hall blocks might want to act as chunk loaders, keeping them active as valid targets even when the player is out of spawn range.

This is what I'm working on at least. There exists a range of mods that can help with raid triggering, including Apocalypse and [Accidentally Circumstantial Events](http://www.curse.com/mc-mods/minecraft/227796-accidentally-circumstantial-events-ace) but it would be great if AW2 had an integrated solution - especially if the vehicles make it back in to the mod. Vehicles really are the priority in my opinion at least, which is why I've not bugged for this functionality. I'm happy experimenting with the tools I currently have available for now.

**Comment by SkiesFallSunder** [comment]
Maybe using a Gui to mark limits? Let's take the 3D map mod for example. It loads a 3D image of the world but you can tilt it so you're looking down onto it. So that 3D map visualizes as a 2D map but you're able to see the exact blocks that are there. I'm quite new to the whole mod scenario and I'm filled with ideas but unfortunately I lack the ability to construct them as I envision. I'm not sure how it would work but maybe it's a possibility to approach it in that matter. Use a 'Outpost' block like most interactive GUI blocks. Display a 3D visual of the map that you can zoom in, tilt, mark areas, buildings, distinguish what is what such as the town hall blocks and such. Use it to configure set paths for guards to walk.

I highly appreciate this mod in many ways though I'm still learning the aspects of it. I'm sure this mod will go far and I would love to have an influence in it.

**Comment by teragen** [comment]
Could always create custom biomes to reflect different aspects of your empire, with some form of outpost marker spreading the biome in a radius around the marker. Could in theory then set behaviour dependant on biome mob is in, and owner of nearest flag. Destroying a marker would shift ownership to whoever owns the next nearest marker.

**Comment by ThatPolishKid99** [comment]
This is kinda off topic from this discussion, but can i suggest something?
Can engineers be temporarily or permanently able to operate a set(s) of levers/buttons?
at least until the Vehicles Module

**Comment by MohawkyMagoo** [comment]
Your problem with any kind of "empire" or "kingdom" set up is that Minecraft is not a persistent world. Nothing happens in chunks that are not loaded. Unless you use chunk loaders of course, but they have a massive performance hit for most peoples machines.
