### ISSUE TITLE
Couriers not working

### ISSUE THREAD

**Issue by BlazeGaming007** [P3pp3rF1y/AncientWarfare2#316]
when ever i give the couriers a routing order i tell them to pick up cobblestone and dirt from the quarry but they go up to the quarry but dont take anything. Then later i told them to pick up non matching items and put nothing in there so as they pick up everything but it doesnt seem to work. It is strange because they were working fine (but often messed up) before i added the quarry to the list of items to take. If there was a limited amount of space they have ,they had the biggest bags possible but they dont pick up anything. Currently i have removed the quarry and another point(TinkerConstruct smeltery).I am testing it now.

I have now tested the things and read the manual multiple times but to no avail.
 Please fix this bug.Also it would be nice if someone could give me a suggestion for now

**Comment by GotoLink** [comment]
Quarries, like all other worksites blocks, are side sensitive. The main inventory is always on the "top" side.
Other worksites have "front" inventories for blocks or seeds, and "bottom" inventories for items.
Since those blocks can rotate, the definition inside the routing order need to match the rotation.

If you selected "Take Non match", without any item match, everything should go into the courier backpack, unless there is no space in said bag. "Dep. non match" should do the opposite, filling the quarry.

**Comment by P3pp3rF1y** [comment]
Closing this is working correctly in 1.12 and sounds like it was setup issue anyway.
