### ISSUE TITLE
Tile Entity Exception notification in console

### ISSUE THREAD

**Issue by Alaberti** [P3pp3rF1y/AncientWarfare2#338]
http://pastebin.com/sEVCucM7

I recently removed some mods from my game, and received this error upon entering an existing world. It says to let the mod author know so uh...here we are. 

Ancient Warfare 106 Forge 14861

**Comment by GotoLink** [comment]
The mods you removed added some items. One of those items was into a warehouse storage unit.
Since it didn't match anything when loading, it is considered a non-recoverable error. (That is, you will permanently lose the item, adding the mod back will not recover it)
You should know that removing mods after a world has been generated is unknown territory. Not even Forge support that kind of thing.
Now that is said, this specific crash can be handled.

**Comment by Alaberti** [comment]
I'm not worried about the items, just helping out where I can.

**Comment by GotoLink** [comment]
Fixed in build 107.
