### ISSUE TITLE
Question - Music/SFX block?

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#340]
Any chance of a quick run down on how the block works, what the settings do, where its supposed to draw its sound list from, what formats it plays - . ogg?   or is it still WIP? 

When I access it, it gives me a selection of very weird stuff from a couple of mods, but nothing like the list it should have, if its just listing MC and Mod sounds loaded? And I cant get it to do anything other than play the same sound over and over, no matter what I set it to.

**Comment by GotoLink** [comment]
The note setting list all sounds that Minecraft knows about.
They are commonly listed in sounds.json. Disc music usually have "records" in their internal name.
The sound is actually played by Minecraft system itself, so ultimately depends on the resource pack installed, and the client audio settings. Which is why length and volume have basic defaults, and may need to be set by the player for best experience.

Yes, the sound list is played over and over. EIther randomly or in order, depending on the "random" checkbox setting. Each sound is spaced by a blank delay, which length is random between "min delay" and "max delay".
The "redstone" checkbox setting make the block sensitive to redstone power, which you can use to make a sound toggle.
The "player entry" checkbox setting make the block sensitive to any player within the "range" setting, where it will play a sound as soon as player is detected.

The block itself has a "camo" feature. Simply right-click the sound block with the block to use for display.

**Comment by MohawkyMagoo** [comment]
So theres no way to get it to play one sound just once and then stop? 

Not sure I understand the sounds.json thing. How do I go about getting it to play .oggs from a specific folder I want to add?

**Comment by MohawkyMagoo** [comment]
So, been experimenting with this for awhile, and sorry to say, in its present form its not really usable for much. It needs some more specific functionality before it would be useable in structure generation.
