### ISSUE TITLE
FakePlayer issues because of unassigned UUID

### ISSUE THREAD

**Issue by olee** [P3pp3rF1y/AncientWarfare2#389]
This is a bug report in regards to previously closed issues #387 and #352

This is actually a problem on your side, because you create invalid FakePlayer entities:
[CommonProxyBase.java#L30](https://github.com/shadowmage45/AncientWarfare2/blob/master/src/main/java/net/shadowmage/ancientwarfare/core/proxy/CommonProxyBase.java#L30)

You are not supposed to pass a `null` UUID.
Either create your own for AncientWarefare and always use the same (which will mean permission for all blocks using FakePlayers will be treated the same), or the correct way would be to change  [IOwnable](https://github.com/shadowmage45/AncientWarfare2/blob/master/src/main/java/net/shadowmage1/ancientwarfare/core/interfaces/IOwnable.java) to save the UUID additionally / instead of the playername.

**Comment by GotoLink** [comment]
Issue 352 is not closed.
The null argument in GameProfile is valid, as shown by Minecraft own usage and implementation of this class.
Though the best effort will be made to support UUID in the future, there is no guarantee UUID will ever be non-null in all cases, due to backward compatibility and the "no-player logged-in" automation module possibilities.
Branch 2.5 is more advanced on this topic, by the way.

**Comment by olee** [comment]
Sounds good if you are already working on progressing to UUIDs.
As I managed to hack in a safeguard in FE for such cases and you are working ont it, you can close this if you like to.
