### ISSUE TITLE
Config not working

### ISSUE THREAD

**Issue by PrettyHeatToast** [P3pp3rF1y/AncientWarfare2#412]
```
# Default = true
# If set to false, research system will be disabled and
# all recipes will be available in normal crafting station.
B:use_research_system=false
```

Even though the above is set to false the recipes are still in AW crafting.

**Comment by PrettyHeatToast** [comment]
It turns out the above config does actually work but adding the gates and NPCs to the config manually doesnt work

**Comment by hron84** [comment]
That config option does not work for me (AW 2.4.113-beta-MC1.7.10-FULL), I changed that to false, but I'm still not able to craft a tree farm nor in AW crafting table nor in normal one.

**Comment by GotoLink** [comment]
Did you reload the game after config change ?

**Comment by hron84** [comment]
Hmmm... I'm not totally sure what could be happened, but it seems to work for me. After the config change I tried to restart the game, but the treefarm recipe still not worked. But now, after a few reload and a base move, I checked it again, and it seems working. However, too much thing happened (e.g, I broke and re-placed the engineering table, re-crafted the book since I accidentally lost it, and many different things), so I could not tell what solved the problem. Maybe a few more restart.
