### ISSUE TITLE
recipe not working

### ISSUE THREAD

**Issue by Paladyne** [P3pp3rF1y/AncientWarfare2#445]
I am testing AW for a possible HQm modpack I am working on and it will not use recipe for the wheel.  In this case I can only see  a difference in a couple items, it asks for "stone" and in my pack it is listed as "stone 1".  "Dropper" is listed as "dropper 158", "hopper" is listed "hopper 154".    Not sure which one is not properly identifying but others have worked fine until now. Planks worked several times before, so I highly doubt they are the culprit.  But it is still possible.
![not registering](https://cloud.githubusercontent.com/assets/16755509/12387464/ebfa6b02-bd89-11e5-9141-d1aafe106539.png)

**Comment by Rosomah** [comment]
I have the same problem.
I'm using the Millenaire mod in addition to this one and I can research every other research but the two:
- The Wheel
- Siege Warfare

I'm thinking the problem is with the wood planks as both researches have them in the recipe and as far as I remember, the other researches didn't need wooden planks.

**Comment by GotoLink** [comment]
Mod version ? Ore dictionary support has been added a long time ago.
Check that within "/assets/ancientwarfare/resources/research_resources.csv" file, "plankWood" is set as ingredients for the research.
Replace in whatever ore name your "stone 1" and "hopper 154" are supposed to have. Those numbers are the legacy block id (http://minecraft.gamepedia.com/Block_id#Block_IDs), thus they aren't particularly useful. Blame on whoever tried to replace those blocks. (not me)

**Comment by Rosomah** [comment]
I can't find ancientwarfare folder in assets.
Mod version is 2.4.114.
And I've tried deleting Millenaire and the recipes still don't work.

**Comment by Anghelos92** [comment]
You must go to the mods folder, then open the ancientwarfare-2.4.114-beta-MC1.7.10-FULL.jar with for example win rar then you should find in it the folder "assets" then find the folder "resources" here you will find .csv files that will let you to modify some resources requirements. The right address is the one provided by GotoLink "/assets/ancientwarfare/resources/research_resources.csv" inside the .jar of the mod. You can edit .csv files with excel or notepad++, maybe even with standard notepad from windows. I hope it will help you.

**Comment by Rosomah** [comment]
OK, thank you. I found the issue in the research_resources.csv
It was with the wood planks. I deleted the requirement for wooden planks and I was then able to research The Wheel. The requirement was something like "woodPlanks,0,4" or something like that. Is it possible that it needs "Oak" to be added at the front? If you could give me an answer I would be glad, but in the meantime I'll try to figure this out by myself.

**Comment by Anghelos92** [comment]
In minecraft wood planks, Like other objects, are not different blocks with different id but blocks with same id but different item damage. For example planks,0 are oak planks, while planks,1 are spruce planks etc. I don't Know why it does not work because it seems that the .csv file is ok because the intention of the mod author is to let use any type of woodplanks. You can try with one of the following:
the_wheel,planks,4
the_wheel,planks,(asterisk symbol),4
the_wheel,plankWood,(asterisk symbol),4
[I don't know why Github don't let me use the asterisk symbol in this comment, however I hope that you understand that you need to use the asterisk key in the keyboard instead of typing asterisk symbol in the.csv file)]
the_wheel,planks,0,4 (this Will Force you to use oak planks)
the_wheel,woodPlanks,0,4 (same as the prevoius) maybe the error in this .csv file is simply the name so you should Write planks instead of plankWood. Hope this help you. Try them because I can't say For sure.

**Comment by Rosomah** [comment]
*

**Comment by Rosomah** [comment]
I tried some of them and the first two worked (although I had to use oak), the third doesn't work and the rest I didn't try, I assume I would have to use oak with all of them anyway so, it's good, the problem is solved. Thank you for your help.

**Comment by Anghelos92** [comment]
No problem, you're welcome :) enjoy the mod!

**Comment by GotoLink** [comment]
Apparently "ore dictionary" doesn't get pickup in planks case. 
Fix coming up soon.

**Comment by Anghelos92** [comment]
Thank you GotoLink, remember to fix also archers and workers that pick up swords, if possible :)

**Comment by Paladyne** [comment]
thank you all very  much, and yes it was the planks, appreciate it. will update AW and try again, this mod is insanely good, and combining with millenaire truely makes it into an awesome modpack.
