### ISSUE TITLE
[Suggestion] vehicles

### ISSUE THREAD

**Issue by kuroikun** [P3pp3rF1y/AncientWarfare2#447]
First of all I want to tell them that not handling very good English and use google translator to write this. Well as it says in the title consider that vehicles were the strong point of this mod as ways to automate farms and other things there are several mods that already have but catapults, ballista, trabuchets and similar things there in any other mod at least not that I know of. So I suggest you re-add at least some, such as siege weapons fixed. From already thank you very much for reading.

**Comment by Anghelos92** [comment]
This issue was already presented, but unfortunately GotoLink has many mods that he is caring of, maybe in a future someone Will add this :) For example I bought a Java manual just some days ago...i have studied first 4 chapters over 20 maybe one day I could be of some help to GotoLink instead of just presenting issues and hope For the best xD LOL...however I subscribe Your request :)

**Comment by kuroikun** [comment]
thank you very much for responding, I hope to have at least achieved the ballista which is my favorite haha, and I hope to do well with java

**Comment by jaker1** [comment]
Yes it would be better if they add vehicle to minecraft 1.7.10.
It's only drawback.

**Comment by jaker1** [comment]
and are they going to make updates

**Comment by P3pp3rF1y** [comment]
closing, vehicles are added in 1.12
