### ISSUE TITLE
Workers wont leave the house

### ISSUE THREAD

**Issue by Simon-Ble** [P3pp3rF1y/AncientWarfare2#453]
For some reason my workers wont leave to go do their job, they will get the emote above their heads to go to a farm, walk to the door then turn back and stand by the town hall for a while, then repeat.

Any Ideas? Ive tried moving the town hall outside, moving the farm inside and killing everyone and remaking the blocks.

Im playing a local server and didnt have this issue the other day while using the mod
Playing Resonant Rise 3

**Comment by Anghelos92** [comment]
I Will assume that you spawned the NPCs near the town hall so that the "home points" ho your NPCs is near Your town hall. This behavoiur can occur if outside is raining because during rain NPCs try go to work but then they retun home once they  exit the door. Maybe, if it's not raining it is possible that there is a Monster nearby  ( maybe under the terrain in a cave near the surface that is detected by Your npcs once they reach the doors so they run back home. You can try setting the difficult setting to peaceful and report Here if this behaviour is still present.

**Comment by P3pp3rF1y** [comment]
Closing haven’t seen anything like this recently in 1.12
