### ISSUE TITLE
Windmills work just fine underground and when enclosed

### ISSUE THREAD

**Issue by Da-Technomancer** [P3pp3rF1y/AncientWarfare2#454]
Windmills make just as much power at y = 5 in a tiny enclosed space as at y = 200 in the sky. This, combined with the fact windmills are more efficient when smaller, results in people making "windmill tunnels" which are underground tunnels of closely packed 5x5 windmills making tons of power/torque. I think windmills should work fine low down, but they should need to be in an open area, and when they are enclosed they should be very inefficient.

**Comment by Anghelos92** [comment]
Yes this should be addressed by someone, unfortunately the mod maintainer (GotoLink) is actually very busy with other mods and the original author Left the project unfinished and bugged so we can only wait and hope (or try to learn java ehehe :) )

**Comment by GotoLink** [comment]
As much as i like realism, this is going to be tough on CPU.
Mostly vanilla isn't made for blocks to have environment interaction.
You can place a furnace underwater or a crafting bench into lava, they are operating fine forever.
Energy needs to be checked regularly, too. Thus the processing cost can't be saved like the windmill construction does.

**Comment by Anghelos92** [comment]
Yes I agree but it could be done something to limit this irrealism: The windmill control block can check if there are no block above it ( in that case it Will not produce Energy ) and it could also check Y level so that with a Y-level < 70 it Will not produce nothing...yes this Will not prevent to create windmill enclosed but at least you have to make them on surface...

**Comment by GotoLink** [comment]
Blocks above or y-level have nothing to do with the described issue. Windmills can work under a roof.
The solution isn't simple. It is air dynamics we are talking about.
And then there is the problem that chunks may not be loaded.

To be clear i am not rejecting the issue. This is simply me taking notes so i don't forget.
-Make windmills burnable (because no, lava isn't safe)
-Design a fast algorithm for air flow in windmill direction (simple pyramid shape ? : 29 blocks for 5_5, 204 blocks for 9_9, 1496 blocks for 17*17, per face)
-Design a work-around unloaded chunks/ Define some default behavior
-Convert to similar energy levels in superflat world
-Scale it among windmill sizes
-Apply on rotation for rendering (if fast enough server side)
