### ISSUE TITLE
Issue with melon stems

### ISSUE THREAD

**Issue by wadewegner** [P3pp3rF1y/AncientWarfare2#455]
I've noticed that automated farms don't harvest melon seeds from melon stems. Something to fix?

**Comment by Anghelos92** [comment]
I think this is intended because Melon and Pumpkin stems are there to stay and generate melons and pumpkins...then from melons pieces and pumpkins harvested you can craft the corrisponding seeds...for example from one pumpkin you can craft 4 pumpkin seeds and from one melon pièce you can craft one melon seed. This is in fact a vanilla minecraft intended use, when you plant melons in vanilla minecraft is supposed that you harvest only the melons and not melons stems because you can have melon seeds from the melons and also because the production of melons is way faster if you leave the melons stem instead of plant ana wait that the melon stem grow new!

**Comment by wadewegner** [comment]
Ah, didn't realize that. So, basically, I need to be more patient and let it turn into a pumpkin or melon? Thanks!

**Comment by Anghelos92** [comment]
Yes but you have to leave 1 block of dirt clear near every stem, i suggest you to see a youtube video about it :)

**Comment by Anghelos92** [comment]
You may see this video http://youtu.be/3Gdnlx1SvNk, hope that help you :)

**Comment by GotoLink** [comment]
Indeed, same goes for cocoa farming which leaves the jungle log alone.

**Comment by wadewegner** [comment]
I don't believe this should be closed. From what I've seen, the crop farm plans melon seeds on every block and doesn't leave any room for the production of melons. I'd say this is a bug -- the farm should leave space open to melon development.

**Comment by Anghelos92** [comment]
I think you did not understand how to make a AW pumpkin/melon farm work, sorry if I were not able to teach you well :( . I will try again: you must create the infrastructure for the farm, melons, pumpkins and cocoa farms are not fully automated yet so you must plant the melons and the pumpkins manually  leaving space for development, or you must place the jungle woods and the cocoa beans on them manually and then you place the farm, you must not insert resources in this type of farm because this farm will continually harvest melons and pumpkins when they develop without th need of planting anything. Think about it: if you harvest carrots you take all the plant and then you must replant it but with melons and pumpkins you do not harvest the melons/pumpkin stems you just harvest the pumpkin or the melon, the same will do the this farm. At the moment this farm is not able to create a correct pumpkin/melon/cocoa layout automatically, so you MUST create a correct shaped farm mnually first and then you place the farm civic which will only harvest the resources. I hope I have helped you, sorry for my bad english xD

**Comment by GotoLink** [comment]
You need not a constant input of seeds for melons and pumkins. Hence you should only give the seeds at the time of creating the farm. Too many seeds will indeed make a crowded farm. You can select non-farming space with the "bounds" GUI of the farm block.

**Comment by wadewegner** [comment]
That's what I needed to know, @GotoLink! Is that documented somewhere? I did not know you could specify non-farming spaces.

Sorry @Anghelos92, but your solution wouldn't work. First off, it's not automated. Second, melons would produce additional seeds that would get picked up and eventually result in seeds that would get planted in empty space.

**Comment by GotoLink** [comment]
Most things are documented in the [user manual](https://github.com/shadowmage45/AncientWarfare2/blob/2.5/project_resources/instruction_manual/instruction_manual_2.3-beta.pdf)
