### ISSUE TITLE
disabling chunk loaders 

### ISSUE THREAD

**Issue by darktrek** [P3pp3rF1y/AncientWarfare2#460]
hi i was wondering if there is a way to disable the chunk loaders, i edited the config like this 

B:"AncientWarfareAutomation:chunk_loader_deluxe"=false
B:"AncientWarfareAutomation:chunk_loader_simple"=false

but i can still give myself them from the nei. is there a way to not make them show up in the nei on my server, it seems they bypass the need to players to be online, 

many thanks

**Comment by cosmicdan** [comment]
That's not a problem with this mod. Disabling items usually disables the recipe for them but keeps the item because (a) Server moderators who can enter creative mode might still want to use them, and (b) it will keep world compatibility if they are later enabled again (or were enabled before on the same world).

If you want to hide it in NEI, use another mod to hide items from NEI. But these are purely client side, they can be unhidden if players change config because NEI is a client-only mod.

If you want chunk loaders for AW2 to not work at all because you have creative-mode players on your server or something, then use forgeChunks.cfg to set available mod tickets to 0.
