### ISSUE TITLE
Suggestion: Prospector

### ISSUE THREAD

**Issue by DcNdrew** [P3pp3rF1y/AncientWarfare2#484]
If you ever played Settlers (Serf City) series, you sure did meet with the prospector who could tell you what kind of resource can you find under the surface.

This guy could be a big help. He would place signs, and write on them the chances of ores under the ground.

I altered the generation of ores so I can't find some of them without Xray. :D Nope, I'm not using Harder Ores with its prospector plants, because its requirement the Custom Ore Generation is a pain.

Ancient Warfare is some kind of strategic mod, so finding resources isn't far from it. You can defend them.

**Comment by cosmicdan** [comment]
AWESOME idea. I loved Settlers (mostly II)!

I might work on this :D

How do you think it's GUI and general control could work though? If you have any ideas for that, do share.

**Comment by DcNdrew** [comment]
I don't think they need much. 
They might need prospector's pick, it's material will tell what kind of resources can they find. 
You would make a work order, a paper, right click on a block which would tell them which chunk need to be examined or the center of a given wide circle. Choose the easiest one. :D
They go out to the location, start to work. The pick decides what can they find.
For example wooden pick will give clay, sand, coal. Stone gives coal, and iron.
Iron gives gold, iron, coal, lapis, redstone. 
Golden gives diamond and netherquartz to the iron's list.
Diamond will let them search much wider.

This could be the default setting for those who use only the vanilla ores.
For more ores we might give them more tiers, and those should be configured as we'd like.
The config doesn't need much either. Name of the pick, and the list of the searchable blocks.

**Comment by DcNdrew** [comment]
Well, one more thing: I don't know if you can set how fast should they work, but you would configure the limit how much blocks do they examine in a tick.
So they will work for a while. :D

**Comment by GotoLink** [comment]
All vanilla ores except emerald have chances of generating independent of the area.
This is pretty much useless outside of custom generation.
And consider you could build quarry and collect ores with about the same requirements, i don't see this being used at all.

**Comment by cosmicdan** [comment]
Good point about it being only useful for custom ore generation I.e. large and rare veins. But that's how I only play anyway myself, so I am interested in doing this for personal reasons. But as an optional addon since it wont be interesting to many and will just be unnecessary code bloat.

I will see how I go.

As for detecting custom ores, it can be managed automagically as custom ores still have their associated harvestability tier. But yeah, fine tuning with manual configure is always nice, for modpack creators to gate progression and the like.

Regarding speed, the level of the prospector would determine that. But yeah, a config setting to determine the multiplier/rate per level is a given - sure.

On 6 May 2016, GotoLink notifications@github.com wrote:

> All vanilla ores except emerald have chances of generating independent
> of the area.
> This is pretty much useless outside of custom generation.
> And consider you could build quarry and collect ores with about the
> same requirements, i don't see this being used at all.
> 
> ---
> 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/shadowmage45/AncientWarfare2/issues/484#issuecomment-217251714

## 

Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.
