### ISSUE TITLE
update

### ISSUE THREAD

**Issue by erikuz** [P3pp3rF1y/AncientWarfare2#495]
Is there any upgrades soon?

**Comment by erikuz** [comment]
Please!!!!!!!!!!!!!! close your stupid mouse thatpolishkid. This question isn't for you!!!!!

**Comment by ThatPolishKid99** [comment]
For the love of God, please understand what I am trying to tell you on behalf of GotoLink, begging for requests is not the purpose of this issue tracker. This is NOT a forum, this is NOT a community site, this is a code repository and its only purpose is for storing and displaying the code of the mod. The issue tracker is for ACTUAL PROBLEMS WITH THAT CODE, THAT AFFECT HOW THE MOD WORKS.

The answer to your question? No, probably we wont be getting any updates to this mod, as unfortunately, development and updating has come to and end, unless GotoLink suddenly drops something on us. So, please, since I only respond to this because I am trying to help GotoLink by at least not having useless issue reports clogging his inbox, PLEASE STOP

please close this issue

**Comment by erikuz** [comment]
Firstly, sorry for beeing rude.
Secondly, where I can find answers to this kind of questions.

**Comment by ThatPolishKid99** [comment]
The answer is that no, there will be no updates soon
 the last commit was in March, and the last release was in March, and since then its been basically radio silence from GotoLink, so you can assume that development has ceased indefintely. If GotoLink decides to start updating again, then great, but it seems unlikely as of lately

**Comment by erikuz** [comment]
Ok thank you for answering.

**Comment by erikuz** [comment]
If it's possible i will close it now
