### ISSUE TITLE
Several GUIs are missing shift-click functionality (warehouse interface, npc inventory...?)

### ISSUE THREAD

**Issue by Pelirow** [P3pp3rF1y/AncientWarfare2#52]
NPCs, Research Station, Packs... No biggie really, except for the pack.

**Comment by shadowmage45** [comment]
Thx for the report -- yes, several of the GUIs are missing the shift-click code.  Will work on adding these in as I can.

Please note any specific GUIs that shift-clicking doesn't work in -- will need to know which ones to fix :)

**Comment by shadowmage45** [comment]
Specific GUIS:

Backpack (fixed)
Town Hall (fixed)
Research Station (works)
Warehouse Storage (fixed, needs testing on high-latency server)
Warehouse Control (fixed, needs testing on high-latency server)
Warehouse interface
NPC Inventory GUI (unsure how to handle with the many differing item-slot types)

Please make note of any others, will update this ticket as I get them fixed/verified

**Comment by Dulciphi** [comment]
thank you. I was going to mention the backpack here but I'm not sure if it's intended to have shift click.

**Comment by Dulciphi** [comment]
Warehouse Interface doesn't currently have shift click ability. 
Shift click _does_ work for taking items out of the warehouse storage block (it extracts an entire stack at a time) but doesn't allow shift clicking items _into_ the storage block directly.

**Comment by shadowmage45** [comment]
Still needing implementing:
- Sterling Engine/Generator fuel GUI.
- NPC inventory GUI (not quite sure on how to do this one)

**Comment by Dulciphi** [comment]
Re: NPCs - Do you mean with the work orders, armour, weapons/tools, etc?

**Comment by shadowmage45** [comment]
NPCs - Yah.  Not sure how well I'll be able to do that one though, as many of those slots are too 'generic' for most purposes (e.g. the main-hand slot accepts anything...).

So..might be omitting shift-click functionality from that one.

**Comment by Dulciphi** [comment]
I'm not bothered by it myself but I can see its advantage. Eg I noticed xtremetom accidentally put a bow in the shield slot in his video then thought the soldier was broken. But it would require limiting what _could_ be placed in the slots? And then (negative consequences that I can't foresee or comprehend go here). 
But if you're sure it's a bug (re:NPCs) and there's an appropriate example that can easily be emulated, then do. Otherwise your time might be better spent rebuking me for presuming to tell you how to spend your time. ;)

**Comment by shadowmage45** [comment]
Regarding the main and offhand slots -- I am purposefully -not- validating those slots, so that players may equip cosmetic items to their NPCs if they wish.  Probably not the most useful for most survival-mode uses, but could be of great use for designing a custom boss-type NPC for use in structures.  It would also be extremely difficult to do it effectively while still allowing inter-mod compatibility -- as there is no base 'weapon' item class, I would need to special case -every- item that could potentially be put into the slot.

The other slots should -already- be validated -- e.g. you cannot place boot armor into the head armor slot, nor place a sword into any armor slot (they only accept armor).

So, I guess upon further consideration -- no, I probably won't be adding any shift-click to NPC inventories.  i will try and make better note of what items go in what slots (either through tooltip / instruction manual / etc)
