### ISSUE TITLE
[1.12.2] Unclear config comments

### ISSUE THREAD

**Issue by PhoenixRiver** [P3pp3rF1y/AncientWarfare2#570]
The following comment and default in AncientWarfareNPCFood.cfg suggests that nothing will be treated as food except those things in the exception list above (since multiplying by zero is always zero and therefore the thing is treated as non-food) since the default exception list contains only apples and mushroom stew as exceptions even vanilla bread would be worth nothing as a food... this doesn't seem right! I'm confused! Sorry :(

```
default {
    # Food items which don't have a custom duration time set will have their nourishing amount multiplied by this number, to get the number of ticks feeding the npc. [range: 0 ~ 214748364, default: 0]
    I:"Food Multiplier"=0
}
```

**Comment by CrashHermit** [comment]
I too am confused by the wording of this, also I am confused on what counts as nourishment. Is it the hunger restored, saturation restored or some combination of each?

**Comment by P3pp3rF1y** [comment]
Looking at this after a year some things may have changed in the meantime, but the default value is actually 750 and I don't remember changing it so I guess it must have been modified in your modpack. Otherwise the comment is accurate, any food that doesn't have a specific feeding time set will use this multiplier to multiply nourishment of the food to get the feeding time.
