### ISSUE TITLE
[How To] Use Mailbox to auto-load items into warehouse?

### ISSUE THREAD

**Issue by wadewegner** [P3pp3rF1y/AncientWarfare2#594]
I know that in previous versions for Ancient Warfare I was able to get this to work, but I'm struggling right now. Basically, I want to have materials harvested (e.g. mining or farming) automatically deposited into my warehouse.

Under my mining station I place a hopper, and under the hopper a mailbox. The mailbox sets the target to another mailbox that's near my warehouse. So far so good.

But now I want to have the mailbox in the warehouse to automatically deposit. This isn't working. Either something has changed or I'm forgetting how to do it.

I put the mailbox on a hopper. Items drop out of the mailbox as expected.

However, I can't seem to get the items from the hopper into the warehouse. I've tried to go directly into a Warehouse Interface (which is how I thought it was supposed to work) ...

![image](https://user-images.githubusercontent.com/746259/35568585-61ad789c-057e-11e8-83e0-f6a71d6375af.png)

... but nothing that is put into the Warehouse Interface is then deposited into the warehouse.

I have also tried to go directly against the Warehouse Control Block (which doesn't seem right at all) and the Warehouse Storage Block, but even that isn't working.

And yes, I do have energy going to the Warehouse Control Block:

![image](https://user-images.githubusercontent.com/746259/35568661-93a53aba-057e-11e8-9afe-e1d831c6e8ae.png)

Any thoughts from folks on how to get this to work properly?

Thanks!

@P3pp3rF1y: Perhaps we should add an item to take the PDF and turn it into markdown in a wiki so it's easier to update?

**Comment by P3pp3rF1y** [comment]
Seems like the interface is borked a bit for some reason and doesn't run the import logic. Once I am done with fixing the dropping behavior for all blocks I will take a look and fix that as well. 

And yes wiki and/or in game book is on my long list of things to do, feel free to enter an item for that. I am almost starting to think we will need a Kanban board or something like that as just having a big pile of issues isn't very organized. (I keep onenote pages with notes for myself but that obviously isn't going to work for you).

And would really be nice to be able to use a better platform to chat about this stuff rather than using issue comments. As I said I am on a number of them, feel free to suggest what works for you.

**Comment by AwesomeAnimationGamer** [comment]
Is this still broken? I'm running version 1.12.2 and mod version 2.7.0.772 and items will not import from the interface to the warehouse: 
![image](https://user-images.githubusercontent.com/13543820/69461661-11c13280-0d45-11ea-8d6a-71241c133cf4.png)

**Comment by shivachirr** [comment]
as far as i can tell yes

**Comment by ThatPolishKid99** [comment]
I don’t think this is broken in the current version, you should make sure your warehouse is powered and has storage space

**Comment by shivachirr** [comment]
as far as i can tell yes everything goes into the crafting square via hopper of the interface and nothing goes into the controller via hopper or anything

edit now the interface works weridly but kinda wish i could the pipe transpot system to acess the warehouse inventorys as well

**Comment by ThatPolishKid99** [comment]
The interface is the only way to automate item transfer for the warehouse. Any item put into it will be placed into the warehouse unless it matches a set filter in the interface. If the interface has a filter, the warehouse will attempt to fill that interface with those amounts and items from the storage. In order to move these items back and forth, the warehouse control block must be powered. Please read the in game manual, the Treatise on Principles of Ruling, or the online wiki version on this GitHub
