### ISSUE TITLE
Warehouse not saving properly on server close

### ISSUE THREAD

**Issue by lorewalkercho** [P3pp3rF1y/AncientWarfare2#595]
I have a warehouse on a testing server for a modpack I'm working on. When I use the Stop command on the server, the warehouse saves properly. But if I hibernate the laptop I have the remote console on, the server eventually shuts down. Blocks and my inventory are saved properly, so the world is being saved. But warehouse inventory is NOT properly recorded; I've pulled the same stack of 45 sugar canes from it three times in the past few days. I don't have any chunk-loading in active use on this world, either. I can test on a more minimal pack or provide more info on forge/mods being used if needed.

**Comment by P3pp3rF1y** [comment]
Well, I have just retested and warehouse storage is properly being marked to be saved the next time mc saves data and then it gets triggered when all data gets saved including player's inventory. 
So I am guessing that if by shut down you mean that the server crashes (or gets forcibly shut down by the system without it waiting for server to complete) it is able to go through some of the saves but not all.
Let me know if you can recreate this without that hibernate quirk or what exactly the system does to the server there so that I can try to recreate.

**Comment by P3pp3rF1y** [comment]
Closing as there was no additional update
