### ISSUE TITLE
Tree Farm Block not properly saving adjusted work zones

### ISSUE THREAD

**Issue by Pelirow** [P3pp3rF1y/AncientWarfare2#60]
I changed the work area from all "X" to just 10 X in the area, expecting that the logger would only plant in those 10 spots, it's still planting everywhere. Now that I think about it, maybe this is the issue, as it is deciding to only cut trees on those X spots... I was trying to limit the amount of saplings planted because very few were dropping into the work area to be picked up- my tree farm is not giving me a surplus of saplings like it used too.

**Comment by shadowmage45** [comment]
Ahh -- that problem could explain the worker part as well.  It -should- only plant / harvest on blocks with an X in the target GUI.

I'll investigate this later this evening.  If there is an issue, it is likely effecting all of the other worksites as well.

Yes, if you have too many trees, you will get fewer saplings, as there are fewer leaf-blocks per-tree block (i.e. some of the leaves a tree would generate are -already- generated from nearby trees, or filled with log-blocks from nearby trees).  I've found 25-50% coverage to be the best range to generate just a few extra saplings while still getting a decent amount of logs.

**Comment by shadowmage45** [comment]
Apparently this is caused by not clearing the already-scanned work-blocks when the user changes target blocks.  So, you remove a block, but it was already scanned into the 'plantable' block list..and thus still gets planted.

Will look into changing the way the user-set blocks are validated / updated -- possibly clearing any already scanned blocks whenever the user changes targets.
