### ISSUE TITLE
Lost item after upgrade.

### ISSUE THREAD

**Issue by attilavv** [P3pp3rF1y/AncientWarfare2#600]
At this time, after a all upgrade all item in a "block" is lost.

Large pack : all item
engineering station : storage + research book
For other crafting table : all research book

37 -> 54 ; 37 -> 76 ; 76 -> 90.

**Comment by P3pp3rF1y** [comment]
well, that's why I have change log when I release. I have included comment on this with plenty of exclamation marks to make sure that people will see it. 
The mod is in beta exactly for the reason that breaking changes may still happen and keeping everything backward compatible with the kind of changes that need to be done would require quite a bit of effort that I rather want to spend on something else.
But the inventory should not be touched from now on so you shouldn't see this happening again.
