### ISSUE TITLE
Reduce the amount of buildings generated

### ISSUE THREAD

**Issue by JupiterYourHero** [P3pp3rF1y/AncientWarfare2#625]
As I see it there are a little too many buildings being generated.

**Comment by P3pp3rF1y** [comment]
I will evaluate this as part of review of world gen when I am porting to 1.13

**Comment by MohawkyMagoo** [comment]
The Structure Config controls this - or at least it did in the old 1.7.10   - each structure has a cluster weight in its own template. Whilst in the Structure doc it sets how big the overall cluster should be. So for example Max cluster value 250   means that only structures whose total values add up to 250 will spawn in an area. So, example Hut CV 30  /  Temple CV 100   / Castle CV 120  /  Volcano CV 250   =  The volcano could not spawn with anything else because its individual CV is the whole 250 allowed as max -  but the castle, temple and hut could all spawn together because their CV is 250 or less. 

By setting the individual structures CV's and the Area CV correctly - you can control how many structures spawn and with what frequency. 

You can also change and limit the biomes they are allowed to spawn in in the biome whitelist per structure AWS

**Comment by P3pp3rF1y** [comment]
closing because as @MohawkyMagoo said this is controlled by configs. By default we will set config values to what we believe is a good distribution of structures and if people feel otherwise they can change it in the config to what works for them.
