### ISSUE TITLE
creative GUI not working.

### ISSUE THREAD

**Issue by DownThePipe** [P3pp3rF1y/AncientWarfare2#628]
in creative GUI only the health override work the attack and armor don't work. It'll just return to -1 but for bandit or the other enemies everything work fine. I don't know if it just me.

**Comment by P3pp3rF1y** [comment]
This seems to be on purpose for player owned entities. I guess because for those the usually shouldn't be a reason why someone would modify their properties in creative GUI. Also their armor and attack is dependent on what you give them.
What are you trying to achieve with modifying these values? you feel that player owned entities are not strong enough / don't have enough armor?

**Comment by DownThePipe** [comment]
I was just playing with the stats of my entities but the weapon does not do the exact damage i wanted. also i want to see the skin of my soldier without armor but that they can still survive.
I'm mostly playing in creative.

**Comment by P3pp3rF1y** [comment]
So I am leaning to not implementing a change for this. You can use the other entities where this setting works and get the same behavior as far as I can see unless I am missing anything. Also the mod is being built primarily for survival so that's another reason for me.
If you feel like there's a really good reason this should be working the way you would like to let me know, but otherwise I will just close.

**Comment by P3pp3rF1y** [comment]
Closing
