### ISSUE TITLE
Vehicle shots break high resistance blocks and possible vehicle damage addition

### ISSUE THREAD

**Issue by Varg95** [P3pp3rF1y/AncientWarfare2#638]
-Vehicles/gates should receive damage from more sources. Now the don't get damage from a lot of stuff like attacks from the avatar out the iceberg mod, pittfalls of primal. 

- the shots from the vehicles should check the blast and hardness of blocks. Now the destroy everything would be nice if whe could choose what the destroy.

**Comment by P3pp3rF1y** [comment]
Sorry for late response on this, but could you give a bit more info on this?

As far as I can see vehicles get damaged by direct attacks and explosions. Of course it's hard to get skeleton shooting at them because they are not being targeted by them, but if skeleton shoots vehicle by accident they still get damaged. 

Also when it comes to hardness of blocks explosion ones check for explosion resistance, but just testing stone shots now I got it to break obsidian. I guess I could see some really heavy ones doing that but not in general. I will take a look at that one, but if you tested with something different please let me know.

**Comment by Varg95** [comment]
i mean stuff like fall damage and i used this with primal core and electroblob's wizardy avatar mod and a lot of attack don't harm the gates or weapons. for primal i would suggest the pitfall trap to damage vehicles. Gates should recieve damage from more sources. 

Yah i had my own blocks added and didn't matter which shot it broke the block while it has a hardness of 25 and a blast of 250000 so that not overly realistic. i wish you could tweak it a bit.
