### ISSUE TITLE
[1.12.2][2.5.140] Food bundle uncraftable

### ISSUE THREAD

**Issue by Kazzamkablam** [P3pp3rF1y/AncientWarfare2#641]
For some reason I cannot craft food bundles at all, I have required research and engineering table and book on the slot.

Might be cross mod incompatibility?

Log:
https://pastebin.com/Fu7KtBZL

**Comment by P3pp3rF1y** [comment]
Are you able to recreate with just ancient warfare? If not best would be to figure out what mod is causing it. I really don't have time to go through all of the mods on the list to narrow it down myself.

**Comment by Kazzamkablam** [comment]
I did some more testing and it seems to do that even with no other mods installed, just had JEI, latest forge and ancient warfare on fresh install.

**Comment by Kazzamkablam** [comment]
It seems some other recipes are affected too, can't craft light torque shaft or medium torque shaft.

**Comment by ShinyChunks** [comment]
Hi, I do have the same problem. I can't craft the worker as well...
My research book disappeared in the research station before and I crafted a new one. Maybe the research is missing? But I can't research it again...

**Comment by P3pp3rF1y** [comment]
So this one is my bad. As part of other changes for vehicles I have made some changes to how shaped recipes are displayed in JEI. And apparently I broke them and they were displaying incorrectly since. 
The recipes are there and work, but what you see in JEI is incorrect. 

This is how bundle looks after the fix in dev
![image](https://user-images.githubusercontent.com/2079526/39019983-837a7d8a-442b-11e8-8ddf-f208ffed0b89.png)
