### ISSUE TITLE
[Suggestions] Worksite Upgrades

### ISSUE THREAD

**Issue by Dulciphi** [P3pp3rF1y/AncientWarfare2#69]
A place for people's ideas for worksite upgrades. I'm just going to copy out some of the suggestions already made in the message thread.
- Quarry: internal pick slot for increased block hardness/harvestability upgrade.
- Quarry: water and lava pump/removal modules (Would it possibly require internal tank storage/ability to pipe out lava using other mods or a courier with a bucket?)
- increased inventory storage space
- upgrade inventory size for input slot
- Tool slot for farms; higher tier tools could result in more produce - similar to looting on a sword for animal farms. Is it possible to increase the yield of crops at harvest? A sort of "looting" enchant for the hoe :3 If it is not, then perhaps have a chance for a piece of bonemeal to drop as a bonus when crops are harvested. 
- Other possible methods of fertiliser bonus?
- Varka's suggestion for workbounds size limit upgrade - would allow work bounds to be extended via GUI (without having to break and re-place the worksite block). Initial workbounds size limit would need to be nerfed.  "Place block, open GUI, select area to use for civic" with that farm checkbox system you have for plantable blocks; allow varied sizes based on size upgrade rating. Small is 3x3, medium is 6x6, large is 9x9, etc. (If I can add, 9x9 is a good max size for 3 reasons. 1 being the range of the central water source block to wet the soil, 2 being the ability to keep the area lit, 3 being performance?)
- Add upgrades for accepting buildcraft/UE/Redstone Flux energy in lieu of NPC work.
- warehouse/mailbox integration upgrade; You can take a mailbox and get a postmark for it, give it a GUI as if it were a step on the Courier's routing slip from 1.6.4. It might make the courier worthless, but is an interesting take on the "piping."
- Auto-output upgrade, so your quarry/farm/whatever auto-outputs to a chest. same concern with courier? Too derivative of large technology mods? (possibly duplicated by my suggestion for internal inventory size upgrade)
- Auto-input upgrade for resources. Same problem with courier? Couriers are cool, I don't wan't to replace them. 
- Furnace upgrade? Cooks the meat/fish, smelts the ores, requires coal as an extra resource?
- Tiering priority work broadcast? Workers would IMMEDIATELY abandon current civic if work is available at a civic with a priority upgrade?
- Guard broadcast upgrade; if anything on "hostile mobs" list is nearby it broadcasts some sort of summons to combat npcs?

**Comment by Nozgo** [comment]
"•increased inventory storage space"
"•upgrade inventory size for input slot"
Can already be implemented with current item in vanilla MC. (aka: hopper + another chest) 
You can currently have unlimited storage slots for both input and output with more hoppers and chests... 
Also, if you add the tubes from Buildcraft then the chests don't even have to be close by. Or even use the delivery guy. I just don't think more storage for the site itself is needed.

**Comment by Nozgo** [comment]
•Quarry: internal pick slot for increased block hardness/harvestability upgrade.
Perfect Idea - site can only pick blocks that tool is capable of, skipping all others.

**Comment by Nozgo** [comment]
•Tool slot for farms; higher tier tools could result in more produce - similar to looting on a sword for animal farms. Is it possible to increase the yield of crops at harvest? A sort of "looting" enchant for the hoe :3 If it is not, then perhaps have a chance for a piece of bonemeal to drop as a bonus when crops are harvested. 

•Other possible methods of fertiliser bonus?

Opinion? = Auto Farming is already pretty OP. Is there really a need to OP it more? lol after the first few days in game, I have NEVER said, "damn I wish I could get a lot more food a lot faster....."

**Comment by Nozgo** [comment]
•Varka's suggestion for workbounds size limit upgrade - would allow work bounds to be extended via GUI (without having to break and re-place the worksite block). Initial workbounds size limit would need to be nerfed. "Place block, open GUI, select area to use for civic" with that farm checkbox system you have for plantable blocks; allow varied sizes based on size upgrade rating. Small is 3x3, medium is 6x6, large is 9x9, etc. (If I can add, 9x9 is a good max size for 3 reasons. 1 being the range of the central water source block to wet the soil, 2 being the ability to keep the area lit, 3 being performance?)

Upgrading the worksite size would be very handy.... at a measurable cost......

**Comment by shadowmage45** [comment]
Many good ideas here...

Let me see if I can get the existing bugs squashed over the weekend (couriers/routing/stalling workers), and I'll look into some of this balance/upgrade stuff (few others that I want to include as well).

Most of the posted ideas would be doable in one form or another, and quite a few sound like things worthy of implementing.  Will go over them in more detail when I have a few moments :)

**Comment by shadowmage45** [comment]
So far the upgrades that have been implemented are (9 total):
- Med/Large upgrade for regular worksites
- Med/Large upgrade for quarries (different upgrades, will have different costs)
- Two tiers of enchanted tools -- these provide a minor increased efficiency (speed), and for most sites provided some level of fortune/looting enchant equivalent.
- Three tiers of 'tool quality' upgrade -- these provide a large increase in efficiency and for the quarry determine what blocks can be mined (stone-pick level(no upgrade), iron-pick level, diamond-pick level, or all levels (including all higher mod tiers))

Planned for implementation:
- Basic Chunkloader -- chunkloader for all non-quarry worksites (chunk-loads the work-bounds + work block)
- Quarry Chunkloader -- chunkloader for quarries (will be more expensive, as it is a lot number more chunks being loaded) (chunk-loads the work-bounds + work block)

Will look into:
- Resource inventory upgrades (med/lrg)
- Output inventory upgrades (med/lrg)
- Lava/Water pump module for quarry (not quite sure how this would go...hidden internal tanks? really no room for that information in the GUI anywhere)

Inventory upgrades present problems in implementation -- inventories are not meant to be resized, and is difficult to do properly at load/save time, and write properly laid-out containers/guis for.  

As pointed out though, with hoppers+chests (vanilla stuff), you can expand your slots as much as you need -- that is the reason I designed the re-assignable inventory-side system that I have...you can have up to 5x inputs from and 1x output to chests by using hoppers.  So, I'm not really convinced that it is necessary.  It might still be cool, so that you don't need the chests/hoppers, so I will look into it a bit.  I -might- be able to get something working, will see how much code would be effected.

**Comment by shadowmage45** [comment]
Now the question is -- where do these all fit into the research-system, and how costly should they be?

**Comment by Dulciphi** [comment]
For the tiers of enchanted tools upgrade research, I can only suggest using gold, enderpearl, lapis and obsidian. Possibly even an entire enchanting table. Looting or Fortune can be hard to get - or you may get it first go (having already made the enchanting table and acquired enough XP). I usually have to resort to an enchanted book and an anvil, myself. Still it depends on how costly you want the actual crafting recipe to be so I'm not sure. I'd really like to see steel being used in the making of as many worksite upgrades as is possible/sensible. 

As for where to put it in the research system.. it would have to be after you have NPCs and worksites ..and steel? My only idea would be to drop the worksite upgrades under the heading of "Invention" but, again, that could depend on what you plan to do with the research for the upgrades. Are they bundled as a single research? Or researched individually? 

Also, you're quite right about the inventory upgrades. They don't pass the feasibility or desirability test. Who would've even thought up such a thing? _[me blushes]_.

**Comment by shadowmage45** [comment]
I've re-arranged quite a bit of the research tree to try and ease players into the worksite stuff a bit better.

The crop farm is now granted with the 'agriculture' research (t1).   The medium bounds farm upgrade is t2 (engineering), large is t3 (mathematics).  Quarry has moved from t3 to t2 (engineering).  Quarry upgrades are t3(mining) and t5(machinery).

Tool Quality 1, t2, engineering
Tool Quality 2, t3, construction
Tool Qualtiy 3, t5, refining
Enchanted Tools 1, t3, mathematics
Enchanted Tools 2, t6 mass production
Basic Chunkloader, t3, mathematics
Quarry Chunkloader, t5, Machinery

Still undecided on the recipes for some of the upgrades...but I can probably figure something out something appropriate without too much trouble.

I think I will be going with these upgrades for the first iteration of the system.  I would like to add a few others in time, but would really like to get to the first public release before 2015 :)

**Comment by shadowmage45** [comment]
--Still left to implement:
- Chunkloaders, regular and quarry. 

In consideration:
- auto-output upgrade?
- pump upgrade for quarry?
- possibly make the power-system input ability upgrade related?

**Comment by Dulciphi** [comment]
mmm the possibility to make the power-system input ability upgrade related is the only feature I half like there, but it would require all of the worksites getting the same treatment, else it just doesn't make sense. 
That's just me, though.
You have reminded me of something I wanted to check on ages ago, however, but that was when the server was off. Using the base quarry, letting it mine down past redstone, etc level, THEN upgrading it with a tools upgrade. I'm not sure if the quarry went back and mined the blocks it had missed earlier, or if the whole quarry would need to be replaced in order to mine those harder blocks. That's just a question, though, really. Not a bug. 

A pump would also require a tank system and, though Thermal Expansion has tanks, it's not a requirement, and there's no real use for copious amounts of lava in AW2. I'm having trouble seeing the point. 

Auto-output upgrade, as you mentioned earlier, can already be achieved with a hopper and couriers. It's certainly not lacking in any respect there. 

I'm unsure about the quarry chunkloaders but I'm wondering if there's much point in applying a size upgrade without the area being chunkloaded. Perhaps combine the chunkload ability with the bounds upgrade (essentially combining the recipe as well)?

**Comment by shadowmage45** [comment]
Chunkloaders -- you are correct in that the quarry is not of much use unless it is chunkloaded.  However I'm trying to give players the option to use whatever chunkloading mechanism they desire (whether it be AWs chunkloaders, Chickenchunks, or potentially the chunk-loading-upgrade).  Who knows -- perhaps someone only wants their quarry (or other worksite) chunkloaded while they are actually online (but not necessarily nearby) and use a toggleable chunkloader.

Pumps -- true, not very necessary.  And I'm not sure I could get them to function as I would like anyway, due to liquid blocks that are -outside- the bounds of the quarry flowing into the quarry... not much I can do about removing those (without manipulating blocks outside the bounds....and then what good are the bounds?).

Auto-output -- very true.  Most of the instances I can think of where auto-output would be wanted would not be easily doable anyway (as most of the item-transport tubes do not actually -have- an inventory to auto-output into).

So I guess I will examine the chunkloader upgrades a bit more, start looking into what will be necessary to properly implement them.
