### ISSUE TITLE
[Compat] Underground Biomes Stone Blocks and Quarry

### ISSUE THREAD

**Issue by Thessil** [P3pp3rF1y/AncientWarfare2#694]
When mined by a quarry, certain stone blocks like Andestite are mined as their smooth variant, but when mined by a player they are collected as the cobblestone block type. Only two thirds of the stone types in Underground Biomes have a cobblestone variant.

**Comment by P3pp3rF1y** [comment]
Did an investigation into this and from my point of view the fix is on Underground Biomes side. They override deprecated getDrops method instead of the one that's supposed to be used and that I am using in quarry. 
I could potentially use the deprecated one and revert to what I have currently yet again in the future, but I feel like they should fix this on their side and override the proper one.
