### ISSUE TITLE
Medics too strong

### ISSUE THREAD

**Issue by OhPucy** [P3pp3rF1y/AncientWarfare2#705]
I just realized that medics are invincible against normal mobs like zombies, spiders and skeletons. I`m not sure if it is due to the fact that I placed him down in creative mod but my medic seems to heal himself constantly while fighting mobs. That way he was able to fight 2 skeletons and 3 zombies at the same time on his own and slaughtered all of them simply by healing himself in between punches.
Maybe medics should only be able to heal others or at least heal themselves after not being attacked for x number of ticks?

**Comment by P3pp3rF1y** [comment]
I am really not sure how you have got this happening, but basically as long as medic has a target to attack he can't heal anyone. It's true that medic can resist more because he can heal himself once done attacking, but in my testing 2 zombies almost kill him. So I will need additional info on how to recreate your issue or I will need to just close this as I can't see anything close to what you have described above.

**Comment by WinDanesz** [comment]
Atm medics were in fact too weak, 1939e05 fixed that
