### ISSUE TITLE
[262] java.lang.IllegalArgumentException: Invalid UUID string - Server crash

### ISSUE THREAD

**Issue by Alaberti** [P3pp3rF1y/AncientWarfare2#722]
Dedicated server was recently updated to this version and I received this crash: https://pastebin.com/ZNvtnU6j

Is there anything I can do to get around this?

**Comment by P3pp3rF1y** [comment]
Would you know what AW blocks you have in that world / possibly in chunk that got loaded? Just trying to figure out if I have done something wrong in the data fixer or if the block has corrupted owner data for some reason.

**Comment by Alaberti** [comment]
Unfortunately, no idea. I have about 15 players who are at various points with AW2

**Comment by P3pp3rF1y** [comment]
I have just added logging to that part of the code in case that owner id is corrupted for some reason. It will just log error message with tile name and coords of the block, most probably it is going to still crash afterwards but should allow you to remove that block. Also when you get that log could you share here which tile that is. I would like to give it closer look if there used to be a condition under which the owner id could perhaps be missing. I wasn't able to recreate that in my testing.
Not sure that I want to necessarily release this, but you can grab the latest "unstable" version of the mod here once built https://bintray.com/p3pp3rf1y/maven/AncientWarfare2. It's going to be .263unstable. It's unstable because it's build from dev branch, but there's really just yesterday's release in the build + this logging thing.

**Comment by Alaberti** [comment]
Sorry for the delay, irl hit pretty hard. I dropped the 263unstable onto the server and it loaded up immediately, no crash. I went back to 262 and it also ran just fine. Not sure what happened, but awesome work whatever you did.

**Comment by Alaberti** [comment]
Okay, I think I do have something for you:

https://pastebin.com/akySUJrN

Looks like it's the ancient warfare component and some weird recipe thing with Ender IO, hopefully that log means something to you?

Edit: This issue was on a different server, so it's probably not Ender IO specifically but maybe some kind of recipe handler bug with later versions of forge. This report is with Forge 2729.

**Comment by Alaberti** [comment]
Okay, we're still on the unstable build you linked us and a player did get a crash with a torque shaft it looks like: https://pastebin.com/yyk4zkYc

**Comment by P3pp3rF1y** [comment]
I am not able to recreate either of those last two issues so I am guessing some other mod is causing these. Closing this issue now as the original one is resolved. If you find a way to recreate either of those last two feel free to log a new issue.
