### ISSUE TITLE
[Request] Config Change

### ISSUE THREAD

**Issue by NielsPilgaard** [P3pp3rF1y/AncientWarfare2#724]
Hey! 
I was wondering if you could make either a config for removing items from the registry, or change the existing `08_recipe_details` config to remove items from the registry? Even better would be the possibility to remove modules completely. I'm making a highly themed modpack, and it breaks immersion a bit to see vehicles and bullets in JEI.

I hope you'll consider it :)

**Comment by P3pp3rF1y** [comment]
Removing recipes isn't good enough for you? I mean having the items still there is only good in creative if recipe is removed. Currently the research ones can only be changed so you could possibly change those to use bedrock or something like that to block players from being able to get the items. I will probably add a way to disable the recipes altogether in the future.
Modules are on the list, but not very high in terms of priority.

**Comment by NielsPilgaard** [comment]
It's mostly the principle that there'll be unusable items getting registered, taking up registry IDs and adding to load time (albeit a tiny tiny amount of time). If it's a hassle to make, I fully understand your reluctance :)

**Comment by P3pp3rF1y** [comment]
Yeah I understand that removing items is cleaner from player's point of view and on very simple items it's trivial, but as soon as the item starts to have interaction with other blocks / items it gets way more complicated and to actually know that it works one would need to to do way more testing of the mod. I have something like that in Reliquary and keep running into issues where people disable one item and another blows up on them, because I didn't think of the occasions when some items may be missing.

**Comment by NielsPilgaard** [comment]
Fair enough, thanks anyway :)
