### ISSUE TITLE
cant path right

### ISSUE THREAD

**Issue by CharCharthemonkey** [P3pp3rF1y/AncientWarfare2#727]
the NPCs from ancient warfare 2 cant path down stairs at all and no clue whi since they can walk down them cause i tried to make a sorter but the courier (only 1 i have atm) wouldnt path down the stairs to fill some deep storages so to work around i had to move them above ground
![2018-06-28_23 31 12](https://user-images.githubusercontent.com/30783285/42099125-4a31551a-7b82-11e8-8394-e8661a145806.png)

this shows after i had to move but it now works above ground

**Comment by P3pp3rF1y** [comment]
I will need more on this. How far roughly was it in terms of blocks walked and how far down was it?

**Comment by CharCharthemonkey** [comment]
basically it was like from where hes at in the picture probably 22 blocks total down like 5 stairs maybe and through a doorway but he did actually go down the stairs when i had him set to follow me

**Comment by P3pp3rF1y** [comment]
It depends how many blocks were in the way. The pathing can get very cpu intensive because of all the variants it has to go through so it stops at some point and even with 20 blocks between the two points if there are blocks in the way or different levels it may not find the path in short enough time. I have some notes on pathing enhancements, but will likely just close this one unless it will provide me with some more data on what exact situations it's not working in, that need fixing.

**Comment by CharCharthemonkey** [comment]
![2018-06-29_16 15 44](https://user-images.githubusercontent.com/30783285/42120762-5ce16ae2-7be6-11e8-8bca-5f3bbb29973e.png)
![2018-06-29_16 15 54](https://user-images.githubusercontent.com/30783285/42120763-5df88366-7be6-11e8-8501-6c92b8b319c6.png)
![2018-06-29_16 15 59](https://user-images.githubusercontent.com/30783285/42120764-5f14c1c4-7be6-11e8-8ed5-89f676c8006e.png)
the route starts at the stairs and ends at where the cats are

**Comment by lionkor** [comment]
this is still an issue.
