### ISSUE TITLE
[Request] Changes to Recipe Registration

### ISSUE THREAD

**Issue by NielsPilgaard** [P3pp3rF1y/AncientWarfare2#732]
Hey! 

Would it be possible to move the recipes registration of items to before `PostInit`, or an earlier stage? I'd like to change the recipes that require Minecraft Tools to require equivalent Tinkers' Constuct tools, through the mod Tinkered Hegemony. The recipe gets altered, but it's not registered in JEI, which I believe should be fixed by running the registration earlier. Otherwise, I was informed that registering recipes in the `RegistryEvent.Register` event would handle it automatically.

Reference: https://github.com/asiekierka/TinkeredHegemony/issues/5

**Comment by P3pp3rF1y** [comment]
I actually have the registration of research recipes done in init and regular recipes are done through json files which should use registryevent in forge itself.

However your problem is likely that you're trying to alter research recipes which actually are registered completely separately from regular crafting recipes. I am actually not even sure how tinkered hegemony can alter them as it would need to understand where AW stores or what process it uses to load them. 
To be able to change the research recipes you will need to create research_recipes folder in ancientwarfare config folder and then put changed research recipes in there. The original are in https://github.com/P3pp3rF1y/AncientWarfare2/tree/1.12.x/src/main/resources/assets/ancientwarfare/research_recipes. not sure how easy it would be to switch the vanilla tools for tinker ones though.
Let me know if you have any more questions on this.

**Comment by NielsPilgaard** [comment]
I've disabled research recipes, it's the normal recipes I'm changing. The recipe changes are succesful, it's only JEI that doesn't "sync" to the new recipe. I was hoping your recipe registrations were late so it'd be an easy fix, but seeing as they're not, I'll just modify the recipes in JEI.

Thank you for the quick answer as always :)

**Comment by P3pp3rF1y** [comment]
so when the research is disabled I just register as regular recipes in init. I could possibly try doing the same in the registry event, will just need to double check it's not going to break anything. Would you be able to share the tinkered hegemony config you have used so that I can make sure my change actually does something? Or is it enough to just run the mod?

**Comment by NielsPilgaard** [comment]
Just running it should do the trick.

**Comment by NielsPilgaard** [comment]
Thank you, I appreciate it :)
