### ISSUE TITLE
Support for 1.13?

### ISSUE THREAD

**Issue by wadewegner** [P3pp3rF1y/AncientWarfare2#742]
I'm sure you're working on it. Any planned releases?

I'm also curious, is there an upgrade path from 1.12 to 1.13 on a server w/ AW2?

**Comment by P3pp3rF1y** [comment]
Nope, not working on that one yet. There isn't a version of forge for 1.13 yet and based on what i have heard it's going to take longer than the previous releases because of all the changes. And once that is ready I will need to go through quite a bit of refactoring on my side as well. So my expectation is September the earliest, but so far it sounds more like October/November.

Also I have just checked and looks like there are no name mappings for deobfuscation of vanilla code yet either, which is always the first step before forge can actually start doing their part.

**Comment by P3pp3rF1y** [comment]
And regarding the upgrade from 1.12 to 1.13. I will see about that. If the 1.13 changes won't be too radical and I can keep the migration code small I will make it possible to just upgrade to 1.13. But based on my current understanding of the amount of changes needed it's more likely that there will need to be a world reset needed when upgrading to 1.13 version of AW as there seem to be quite a few quite fundamental changes happening.

**Comment by wadewegner** [comment]
As always, thanks for the thoughtful response. Understood!

**Comment by P3pp3rF1y** [comment]
closing, 1.13 forge still has a long way to go before it will be usable by mods. will work on port then.
