### ISSUE TITLE
Opening Ammo Selection GUI while on a vehicle opens up an empty menu

### ISSUE THREAD

**Issue by ThatPolishKid99** [P3pp3rF1y/AncientWarfare2#760]
As the title states, the menu does not open properly, and instead shows an empty GUI
Opening the Ammo storage section still works by shift right clicking

![image](https://user-images.githubusercontent.com/10103417/43993334-47e3d378-9d51-11e8-875d-3da179cba44b.png)

**Comment by P3pp3rF1y** [comment]
So this is actually caused by no ammo loaded in the vehicle. I have changed the GUI to only show ammo that's loaded instead of a super long list of all ammo that can be shot where it was difficult to see the one you have actually loaded.
It's pretty clear this needs improvement, perhaps just a message "No ammo loaded in the vehicle to select from" displayed similar to how the message is displayed when you can't sleep in bed because it's too early. 
Any ideas?

**Comment by ThatPolishKid99** [comment]
Ya, I think even just a little message when you open the menu, saying no ammo to select, would be prefect
