### ISSUE TITLE
Can not feed cows, Sheep or Pigs. 

### ISSUE THREAD

**Issue by GmanAtheist** [P3pp3rF1y/AncientWarfare2#771]
Went out the game. Made no changes. Went back in and suddenly can not feed animals. See attached video. Minecraft 1.12.2. ancientwarfare-1.12.2-2.6.1.318. 
https://youtu.be/3dIDOyWtm6Y 

Please help.

**Comment by P3pp3rF1y** [comment]
Looks like you must have a mod that replaces wheat / carrots with something else and basically disables the vanilla items.
The logic in animal farm is simple - if items is seeds/wheat/carrot it accepts those in the food slots. So what you're trying to put in isn't vanilla wheat or carrot but something that was added by another mod.
If you can actually recreate with just AW let me know but otherwise you will have to try to figure out what mod is causing this for you.

**Comment by GmanAtheist** [comment]
Thanks for the prompt reply. I will go through my mods. Here is my mods list. Maybe you can give me some advice as to which mod could do this. :-) http://nellspace.co.uk/share/Minecraft%201.12.2.txt

**Comment by GmanAtheist** [comment]
OK. So, I found the problem to be MCMultipart mod and placeableitems mod.  All good in Minecraft world now.
