### ISSUE TITLE
Doors are bugged 

### ISSUE THREAD

**Issue by Dente222** [P3pp3rF1y/AncientWarfare2#775]
All types of doors are buged in some way 
they look normal when they are closed but when you open any type of door its model will move above up to 4 blocks with model frame whish makes the harder to be closed without any button, with Drawbridge its a bit different its model moves away for 3 blocks from its rotation point when its open.

**Comment by ThatPolishKid99** [comment]
Hey there! Could you provide us with screenshots for this? Also, does this occur only with the World Gen strucuture spawned Gates and Drawbridges, or custom ones as well?

EDIT: sorry about the closing/opening!

EDIT 2: I also have to ask what version you are using, because the most recent version does not seem to have this problem, I just tested it myself, all gates and Drawbridges open and close fine
