### ISSUE TITLE
Recipes utilizing chests use minecraft:chest and not "chestWood" ore dictionary entry.

### ISSUE THREAD

**Issue by asiekierka** [P3pp3rF1y/AncientWarfare2#776]
Whle I can work around this with crafting table recipes, it seems my approach is ineffective with AW2's "research recipes".

**Comment by P3pp3rF1y** [comment]
I have this fixed in dev, actually using "chest" ore dict as well as I have fixed all the other stuff that could be ore dicted.
the research recipes are here btw https://github.com/P3pp3rF1y/AncientWarfare2/tree/1.12.x/src/main/resources/assets/ancientwarfare/research_recipes
They use similar support to vanilla recipe ingredients, but are enhanced with the understanding of what research they are dependent on and can support ingredients with stack sizes greater than 1.

**Comment by P3pp3rF1y** [comment]
closing, released several releases back
