### ISSUE TITLE
[enhancement] Torque system textures

### ISSUE THREAD

**Issue by Dulciphi** [P3pp3rF1y/AncientWarfare2#78]
At the moment it is somewhat difficult to identify the input and output sides of the different Torque blocks. The muted pink colouring for the output side is difficult to see in low light areas. Additionally, when connecting a conduit to a flywheel for example, the pink is entirely covered. Would it be possible to have a bolder red colour that skirts the outline of where a conduit connects?

**Comment by shadowmage45** [comment]
Not really....mostly due to how MC handles textures for blocks / ISBR -- I am extremely limited to how I can bind/render textures in the block renderers, and can only use a single texture per-side.  So I could possibly change the existing color, but would still do no good for example on the flywheels/worksites.

However, the current torque-tube models/textures are supposed to be placeholders.  The original idea was to have an actual 3-d model for them, using TESRs, that would much more easily lend itself to telling input from output (model would be slightly different on the output side).  These would also be (optionally) animated to show the power flowing through them.

**Comment by Dulciphi** [comment]
Fair enough. The colour change would be helpful if it's not too much hassle for the short term but those 3D models sound very cool. I'm happy to wait.

**Comment by Dulciphi** [comment]
:) I've just made my first sterling generator and fired it up. I didn't realise it was animated! lol It's absolutely adorable. Is that what you had in mind for the animations of the torque conduits? Some kind of laterally rotating rod thingies (or whatever the layman's term is) extending off the flywheel? So cool. I definitely retract my earlier request for the colour change.

**Comment by Dulciphi** [comment]
Safe to say this issue is closed.
