### ISSUE TITLE
Animal Farm Special Resources Inventory dont work with hoppers/sides

### ISSUE THREAD

**Issue by dldummy** [P3pp3rF1y/AncientWarfare2#786]
ancientwarfare-1.12.2-2.6.1.318 Yess ... now i use the latest .... and Wolfes killing NPC works now thanks ..

I can fill or extract with hopper over the sides from the top and front inventory,
but not from the bottom "Special Resources Inventory" -> as example buckets for milking.

If i insert them by hand in the GUI it works so its not the fault of the bucket.

The same construction with hoppers and the same settings for the sides at the Crop farm work like expected (not with buckets but with matching items) , i can fill/empty all 3 inventorys.

So its seems for me like a bug of the animal farm.

It also didnt worked in the last releas ancientwarfare-1.12.2-2.6.1.298.

**Comment by ThatPolishKid99** [comment]
Hi there! As far as I am aware, there is only one side you can extract items from a Machine with hoppers, and that's the down side, simply because of hoppers work. I may be wrong about that, but I do not think you can set up any machine to have two extract sides of a block. I am not sure how you can work around this issue with hoppers, but I recommend couriers so you can specify which side they should withdraw from. Feel free to post screenshots to help me understand your particular issue. 

Also, please join the Discord, if you haven't already, for quicker responses and help: https://discord.gg/zDufbS

**Comment by dldummy** [comment]
Sorry if i was unclear, but the problem isnt about extraction ... (and i am aware that its the nature of hoppers that they only can extract from above (except uppers and smart hoppers).

MY TOPIC IS: Inserting empty buckets (or anithing else) from NO MATHER WHAT SIDE into Sepecial Inventory  dont work.

And if im remember right ...  even the NPCs who work over the side mechanics too ... cant insert ANYTHING to the Special Resources Inventory (NAMED BOTTOM) from NO SIDE,

Extraction out of the Special Inventory is only tested in the process of narrowing the bug.
There is no real use of EXTRACTING items from the special resources inventory but work in the case of the other farms.

But INSERTING shoulde work ... AND DO in the case of the other farm boxes, EXCEPT the animal farm.

I hope its now more clear what i mean.

**Comment by ThatPolishKid99** [comment]
Hi there, sorry for the delayed response, but have tested this, and you are right, empty buckets cannot be placed into the Special Resources Inventory by automated means. 
Thank you for bringing this to our attention
