### ISSUE TITLE
Warehouse crafting station makes items from thin air...

### ISSUE THREAD

**Issue by ProsperCraft** [P3pp3rF1y/AncientWarfare2#797]
If you put enough materials for one craft and shift click it makes as many of the item as you want without using up the materials.

So far we have had Salis Mudus from Thaumcraft, and picks from adventurers toolbox, 

Dreminion may have contacted you.

![2018-09-04_10 48 32](https://user-images.githubusercontent.com/4427684/45050132-c0445f00-b03d-11e8-8a45-d6afaee08a94.png)

**Comment by ThatPolishKid99** [comment]
Hi there! I have been trying to replicate this, but I have been unable to do so. I have tested with various vanilla recipes, and quite a few from other mods, although, I admit, not those specific items. Can I ask which version of AW are you using? Also, please try other recipes, from both vanilla and mods, to check for us if it is those specific recipes, or other ones. I hope this is not too much "homework" for you :D. 
Also, I do not feel comfortable calling this a fluke, as I think someone else mentioned it on the Discord... and speaking of the Discord, feel free to join it and get quicker responses and community help: https://discord.gg/6eNPtgX

**Comment by ProsperCraft** [comment]
Sorry, the environment is listed in the prior bug report - https://github.com/P3pp3rF1y/AncientWarfare2/issues/796

**Comment by Dreminon** [comment]
The only recipes this happened to me on was the salis mundus (Thaumcraft) and iron pick from Adventure toolkit. had enough items to make 3 salis mundus in my system when i shift click it will give me a stack of salis mundus without even using the items i had. same for the pick. I put the pickaxe head and two sticks (only having the one pickaxe head) and it would make as many as I wanted.

**Comment by P3pp3rF1y** [comment]
So the reason this happens is because Salis Mundus recipe actually doesn't have any ingredients so the logic in warehouse crafting that figures out if all needed ingredients are present actually finds there's no need to pull any resources at all. 
The adventure toolkit pick is the same thing, they don't properly set ingredients for their recipes and thus their recipes have no ingredients by default. 
The only logic both of these have is trying to match the contents of the crafting grid to their recipe which makes them work in regular crafting grids, but any grid that actually needs to refill ingredients will have issues with these.
I have implemented a bit of logic on my side to consider these recipes invalid which makes them not try to refill from crafter inventories, so for these you will have to always add ingredients in the crafting grid.

But to really fix this Thaumcraft and Adventurer's toolbox need to fix their recipes to actually include set of ingredients that are required for those recipes.

**Comment by ProsperCraft** [comment]
Something I just also noticed about this bug is it fills stacks of the resources in the warehouse.

I had 7 flint, and it changed it to 64, and 17 bowls and now I have 64 of them as well.

**Comment by P3pp3rF1y** [comment]
Yup that would happen because the logic works like this - take from inventory needed ingredients, craft, return all ingredients returned in remaining items back to inventory.
Which means with 0 ingredients needed you never consume any ingredients, but you continue getting “back” remaining flint and bowls.
