### ISSUE TITLE
When holding a book you cannot open the research table

### ISSUE THREAD

**Issue by Nozgo** [P3pp3rF1y/AncientWarfare2#8]
You can open the table if you empty your hand or if your holding other objects, just not a research book.

**Comment by shadowmage45** [comment]
That is actually an intentional effect of all of my clickable items.  I was sick of them not working while having blocks targeted (specifically, the items that need to target blocks), so I made sure that the items take preference to blocks.  I might be able to investigate excluding certain items at some point that do not need block-targeting capabilities, but for the initial releases this is how it will be for all clickable items.

**Comment by shadowmage45** [comment]
Update:

Intentional behavior.  

Also, I have decided that I quite like the fact that the items are useable consistently -- i.e. the item activates regardless of what block you are targeting.  It always bugged me that the chest i was looking at would activate instead of the item I was trying to use.
