### ISSUE TITLE
Draconic evolution staff of power

### ISSUE THREAD

**Issue by BadLucKWyvern** [P3pp3rF1y/AncientWarfare2#800]
The draconic evolution staff of power is a mix of a Showel, a Pickaxe and a sword, that weapon is considered as an axe and makes the Owning NPC a Medic instead of a miner, or a soldier
This weapon have got a lot of damages and its able to mine any possible ores

Request: Fix the Staff to make the NPC a soldier instead of a medic
(medic healing propertirs with the staff are verygood, at elast, if we could get the choice of the class...

**Comment by ThatPolishKid99** [comment]
So, while the tool of an NPC doesn't really affect the ores it can mine, or affect the healing properties of the medic. the damage of the weapon does transfer to the soldier, but only its actual attack stat, no other special properties will make a difference. I can say this is a compatibility issue and not much else.

**Comment by BadLucKWyvern** [comment]
The real question is why a swordshovelpickaxe is reconized as an axe for the NPC ? :D

**Comment by P3pp3rF1y** [comment]
That's easy axe is the first thing that gets checked and thus if the item is axe the npc becomes medic.
And to be hones I see no reason to make a change specifically for staff of power. If you want you can give soldiers draconic swords, they may be less powerful, but are also overpowered. 
I could change the order of recognizing the tools/weapons, but I am pretty sure that the "right" order would depend on what the player would like to do and really there's always an alternative to use a tool that's focused instead of "do it all" tool.
