### ISSUE TITLE
Hold a better builders wand in your hand and look at a windmill. - Client Crash- 

### ISSUE THREAD

**Issue by ProsperCraft** [P3pp3rF1y/AncientWarfare2#814]
https://paste.dimdev.org/uqugojeyex.mccrash

Modpack - [Ancient TownCraft ](https://minecraft.curseforge.com/projects/ancient-towncraft/)

java.lang.ArrayIndexOutOfBoundsException: 54
    at net.shadowmage.ancientwarfare.automation.block.TorqueTier.byMetadata(TorqueTier.java:24)
    at net.shadowmage.ancientwarfare.automation.block.BlockTorqueTransport.getStateFromMeta(BlockTorqueTransport.java:37)
    at net.shadowmage.ancientwarfare.automation.block.BlockTorqueTransport.getStateForPlacement(BlockTorqueTransport.java:47)

**Comment by BadLucKWyvern** [comment]
Ahahah, very fun, i never thought about it
I have the same issue :D
Im using Better Builder Wands mod

**Comment by P3pp3rF1y** [comment]
I will need more specifics on this one as I am not able to recreate. I have tried pointing it at windmill blocks as suggested, but because the crash log actually suggests this crashed with torque I have tried pointing it at every single torque thing in the windmill as well as tried placing a few myself and point the wand at those. I have also tried the same in multiplayer as well. 

What I also find rather odd is that in the official better builder's wands repo I can't find the call that was made to AW code from bbw code in your crash log - net.shadowmage.ancientwarfare.automation.block.BlockTorqueTransport.getStateForPlacement. 
It almost seems like you're not using the official build from curseforge, but some custom build that has this call.

**Comment by BadLucKWyvern** [comment]
personnaly i do. i take all my mods on curseforge, maybe i should update it if it has been recently updated

**Comment by ProsperCraft** [comment]
BetterBuildersWands-1.12-0.12.0.251+d6c4d93.jar

Latest build off curseforge, using the official twitch launcher.

**Comment by P3pp3rF1y** [comment]
Ok but I still need more info on how to recreate as I have described above.

**Comment by P3pp3rF1y** [comment]
have you seen this one happening again?
