### ISSUE TITLE
Crop farm stops harvesting in certain circumstances

### ISSUE THREAD

**Issue by arel37** [P3pp3rF1y/AncientWarfare2#817]
They stop working when they harvest 1 single reed or cacti. They dont even accept mushrooms.

Please bring back the old farms.

**Comment by P3pp3rF1y** [comment]
so first of all old farms are not coming back, there's no need for them.

As for the crop farm stopping I found out an issue when in certain combinations of blocks the farm would get stuck in the loop of trying to plant stuff in the spots where it can't and not allowed harvesting, fertilization logic to do anything. I have that fixed in dev.

As for the mushrooms, there's no need for mushrooms to be accepted in crop farm slots as if it had capability to plant these it would immediately harvest them. Crop farm harvests small shrooms so you need to let them spread into the crop farm bounding box.

If you actually want to grow big mushrooms you need to use tree farm which accepts small ones in the sapling slots, fertilizes them and then is able to cut down the big ones when they grow.

**Comment by arel37** [comment]
Mushroom farms are not supposed to be giant mushroom farms. Mushrooms spread to adjanent blocks if it is dark enough. Thats why there was a mushroom farm.

For reeds and cactuses, they are not crops, they do not grow on tilled soils. Crop farms tries to till land for seeds. Why are you acting reeds and cactuses as crops? Just bring back the old farms and you wont need to fix or adjust anything. The removal had no sense at all.

**Comment by ThatPolishKid99** [comment]
Regardless of your personal opinion, the old farms will likely remain removed, since their functionality has been given to the crop farm, as P3pp3rF1y decided to consolidate the number of machines
Everything that was accomplished by those old farms can be accomplished by the crop farm now, I’m not sure what your issue is 
The mushroom farm will work just the same with the crop farm, simply set up the mushroom farm to grow into the bounds. 
Cactus grows on sand only, so the crop farm will not till that, obviously 
The only issue I could possibly see with sugarcane is if you use grass/dirt as your planting surface, which could be tilled, preventing sugar cane planting, but I have yet to test that theory 
And finally, the removal was done to simplify the machine list, so it does make sense. The name being crop farm is not a huge deal, and if you’re upset with the development, which is crazy since P3pp3rF1y literally brought this mod back to life, simply don’t use this mod

**Comment by arel37** [comment]
Crop farms not accepting mushrooms at all. Previous mushroom farms had planted mushrooms in red bounds and harvested it in black bounds.
