### ISSUE TITLE
Work order not working on Warehouse Interface

### ISSUE THREAD

**Issue by OhPucy** [P3pp3rF1y/AncientWarfare2#859]
Assigning a Warehouse Interface with "Z" as a workstation in the Work Order seems to be working (at least the picture and coordinates appear in the list).
Giving the Work Order too a Craftsman makes him go too the coordinates and plays the working animation but the worksite itself is not getting worked at (items stay in the Warehouse Interface).

How to recreate:
1. Let a Courier fill the Warehouse Interface
2. Select the Warehouse Interface as a worksite with "Z" in the Work Order
3. Give Work Order too a Craftsman

Taking the Work Order away from the Craftsman solves the problem but he has to choose the Warehouse Interface himself for it being worked on.

**Comment by ThatPolishKid99** [comment]
First off, please join our discord for quicker problem solving: https://discord.gg/ebZskE7

To answer your question, the Warehouse Interface is not what need to be worked on, the Warehouse Control Block is. A Craftsman working at the Control Block will move all items into and out of the Interfaces. However, I recommend using a Windmill to power your warehouse since it can be quite power intensive.
