### ISSUE TITLE
Excesive ammount of NPC

### ISSUE THREAD

**Issue by werff** [P3pp3rF1y/AncientWarfare2#865]
Hi, first of all, I love the new update, but I find that the ammount of NPC inside each new structure is very high, in some of them you can't walk properly and/or the ammount of enemies inside is near, or over, the hundred mark.
Also there are some NPC that spawn RIGHT IN YOU FACE... So, just in the moment you manage to make it spawn, it spawns within 1 to 3 bocks of you...

Yes, I have made myself ally of some factions in order to test the new structures XD

**Comment by MohawkyMagoo** [comment]
Ok, so there are so many things wrong here. Firstly, there are no structures that have anywhere near 100 NPC's. Secondly, by making yourself an ally of the hostile factions you are in fact circumventing the system and making them spawn in ways they are not meant to - essentially you are a player and they spawn in response to that, but then cannot kill you because you have made yourself "invulnerable". In a normal game you would encounter these NPC's a few at a time and fight them. On top of this some structures have "continuous" vanilla like spawners - which are designed to give a combat experience of higher difficulty until players destroy the spawner block - which is plainly visible.  You sitting there as a false ally, making it function improperly is probably the only way you will see "hundreds of NPC's" in a structure. 

There are some hidden NPC's - such as in alcoves and around corners that may spawn in 3 blocks range, but not many, and its deliberate design.

You are seeing these problems because you are causing them, not by playing the game as intended.

**Comment by werff** [comment]
Ok, for the allying some of them, ok could cause problems, but that was for some testing I wanted to do, realted to an MP server.

Second, in a lot of the "Empire" structures, I have counted, while killing them (without any kind of alingment modification) hundreds.

The thing about them loading that way, was a server side effect, that we had with the "ancientwarfare-1.12.2-2.7.0.497.jar", which caused that problem server side (for us), and when loading the world.

Still, in some of the empire structures you can reach a 100 NPC loaded, in a very tight space, generating lag spikes.
So the only real problem, is that some of the "Empire structures" have a lot of NPC, which causes a lag cascade.

**Comment by MohawkyMagoo** [comment]
Nope, sorry, no structure has anywhere near 100 npcs. And from the original description above, you generated those "hundreds" by forcibly joining an NPC faction and letting its continuous spawners run wild.

**Comment by P3pp3rF1y** [comment]
closing this, we have got enhancements in that will make npcs turn back into spawners as well as stop continuous spawners from spawning npcs of friendly faction which should cut on number of entities existing in the world at the same time.
