### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by Mantafisch** [P3pp3rF1y/AncientWarfare2#867]
Anyone must be responsible now to make the mod compatible? : D
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3877

crash:
https://pastebin.com/D2etsPJK

**Comment by P3pp3rF1y** [comment]
The only possible explanation I have for you for this one is that some other mod is trying to register AW blocks for use in AE spatial storage and that's when it crashes. Also you're using an outdated version of AW and if this is really a crash because that other mod is trying to register AW sound block then that issue was fixed in the latest version. 
If that doesn't help there's nothing more we can do here without knowing what mod is doing that.

**Comment by Mantafisch** [comment]
the new version has probably solved the problem. thank you nevertheless for the help
