### ISSUE TITLE
Problems with spawn of npcs

### ISSUE THREAD

**Issue by Aztecoos** [P3pp3rF1y/AncientWarfare2#875]
I downloaded the latest version of the mod. There are very nice structures, but without npcs in this structures. There are only Mob Spawners.

**Comment by TheShadowedTruth** [comment]
![2018-12-30_10 19 07](https://user-images.githubusercontent.com/37980887/50549080-5f5c1a80-0c1c-11e9-82a5-076fedfc5b54.png)
Here is a picture of what it looks like if this helps.  I was actually going to the discord to post about this, when I saw this github notice.  If you need, I can provide a list of mods, I am using, if one of them may be interfering. Let me know.

**Comment by ThatPolishKid99** [comment]
Hey guys, this actually intended. When you’re in creative the spawners are set to not spawn their entity. If you go to survival, you’ll see that they do spawn correctly 
Also, I would recommend reporting on the discord before posting to the GitHub issue tracker, since this is now the second separate issue posted here about this “bug” :D

**Comment by Aztecoos** [comment]
Thanks, now everything is fine
