### ISSUE TITLE
Drawing station and drawing

### ISSUE THREAD

**Issue by Aztecoos** [P3pp3rF1y/AncientWarfare2#876]
There is it possible to create a drawing on the drawing station, the downloaded schema construction, and if so, how to do it?

**Comment by ThatPolishKid99** [comment]
Hi, I’m going to assume you mean the drafting station. In order to add structures to the drafting station, you need to scan the structure, and while in validation, set it to survival.
You can learn about how to do this in our discord server, in the manual chat, where you can find PDFs on how to do it
Here is the link: https://discord.gg/aJdz4x9
Please keep the issue tracker for actual issues, thank you
