### ISSUE TITLE
Potential problem with town generation - or I'm just stupid

### ISSUE THREAD

**Issue by SuspiciousMango** [P3pp3rF1y/AncientWarfare2#888]
Ever since updating to the AW version that added all the new factions and structures (2.7.0.497 I believe) the massive walled (and unwalled) "towns" that used to spawn everywhere have dissapeared. I've flown far and wide in creative and haven't seen a single one, and yet the config still says that "town generation" is a thing (even after deleting and recreating the config files). 

Have towns actually been removed from the mod? If so, I would like to request that they come back. All the faction stuff is cool, but it would also be nice to have default villagers running around in those massive cities. Vanilla villages are just not cool.

If towns haven't been removed, I'd love some guidance on what I'm doing wrong to not be able to find them. Are they just super rare now (I tried doubling the percent chance to spawn in the config file and it seemed to do nothing) or is it some bug with the structure spawner that makes it so I can't find them.

Any help is appreciated. The new structures are beautiful but I would really like the old towns back.

**Comment by ThatPolishKid99** [comment]
Hi there! First off I would recommend joining our discord for quicker responses: https://discord.gg/aJdz4x9

Second, yes, currently all towns are removed from the new default structure pack, but they will be  eventually coming back in new styles and sizes, as part of our structure revamp 
However, they will not contain any vanilla villagers, since we have decided to go with the AW NPC factions as the focus of the structure generation.
