### ISSUE TITLE
[Request] Config to Disable Certain Factions

### ISSUE THREAD

**Issue by NielsPilgaard** [P3pp3rF1y/AncientWarfare2#900]
Hello o/

Would it be possible to get a config option for disabling specific factions? A lot of them don't really fit into the theme of my modpack, but I'd like to keep some of them.

**Comment by P3pp3rF1y** [comment]
So this is probably more a question of disabling specific structures, because the only way we spawn factions in is through structures so far. Best way to do that is just turn off default pack and then copy whatever you would like to keep from https://github.com/P3pp3rF1y/AncientWarfare2/tree/1.12.x/src/main/resources/assets/ancientwarfare/template/mohawky_structure_pack into config/ancientwarfare/structures/included. The structures are categorized by factions / mods / vanilla kind of category (the mod ones will only load if the mod is in the pack, but no need for you to include those that are for a mod you don't have).

btw, we have a really active discord so feel free to stop by if you have more questions https://discord.gg/jNhkDfU

**Comment by NielsPilgaard** [comment]
Awesome, thank you very much!
