### ISSUE TITLE
NPC Can't naturally produced

### ISSUE THREAD

**Issue by Huaxidesu** [P3pp3rF1y/AncientWarfare2#926]
Look this picture
https://upload.cc/i1/2019/03/27/54ptNi.png
https://upload.cc/i1/2019/03/27/j2UOK8.png
 "version": "1.12.2-2.7.0.574",
forge:1.12.2-14.23.5.2815

**Comment by WinDanesz** [comment]
Are you in creative? NPCs does not spawn when you are in creative mode, only their nametag is visible.

**Comment by WinDanesz** [comment]
This way it allows builders of structures to position NPC's and set their spawn distances for staged progression style gameplay to prevent all the NPC's of a structure all spawning at once and rushing you as a big mob.  Its also much better performance wise - as it prevents all those NPC's spawning if you are generating a world by flying around. Its also much better game-play wise as those NPC's don't get killed off by mobs etc just because you passed a structure and didn't go in.

**Comment by Huaxidesu** [comment]
Thanks. That's so cool.
