### ISSUE TITLE
[wishful thinking] Possibly consider adding Harvestcraft support

### ISSUE THREAD

**Issue by Dulciphi** [P3pp3rF1y/AncientWarfare2#93]
Unsure if this is possible but Pam recently added support for MFR, Thaumcraft golems, etc so I'm hoping there may be a way to get harvestcraft crops working with AW's crop farm. If this were possible, would it be something that needed to be done at your end or Pam's?

**Comment by shadowmage45** [comment]
Possible - yes.

Likely - no.

It comes down to the way Minecraft items are implemented.  All uses of 'use this item here' code rely on having a reference to a Player.  Since I do not have a 'Player' in my worksites, I have had to manually map each resource type (seed/carrot/potato) to what block it plants (wheat/carrot/potato), and do all block-changing operations manually.

So without knowing in advance what type of crop-block each seed planted, there is no way to do it.  Even with that I would have to have a HARD dependency on Pams' as I would need to directly reference the blocks and items.  Meaning no AW without Pams' installed.  Not really something I am willing to consider.

Additionally there are issues regarding detecting when the crop block is 'harvestable'.  Vanilla blocks all use a specific metadata to denote 'fully grown'.  There is no guarantee that any mod-added blocks would use the same metadata (or even use metadata!).

So...not going to happen until Minecraft redesigns its item-use/interaction system to not rely on players (yah right..Mojang change code to make mod easier...LOLOLOL) AND mods can all agree on a set way of doing crop blocks (good luck with that).
