### ISSUE TITLE
My own battle Npcs do not take damage or strike 

### ISSUE THREAD

**Issue by MrKissel** [P3pp3rF1y/AncientWarfare2#938]
They do not take any damage from other npc or player but take dmg from fire or blast.
1.12.2

**Comment by MrKissel** [comment]
It is well known issue and it doesnt work on pirate versions

**Comment by Zwasco** [comment]
is there a fix ?

**Comment by MohawkyMagoo** [comment]
Zwasco - This is due to the user having a pirated or cracked version of Minecraft / and or the T-Launcher.  This is not our problem and dont expect any sympathy. The NPCs take their hostility stance from the owner, and if the owner doesn’t have a UUID as pirated copies don’t, then they have no hostility to anything. So they won’t attack or be hurt by anything. This is not a bug, its not something we need to fix or worry about - buy a copy of the game cheapskate!
