### ISSUE TITLE
Structure Survival

### ISSUE THREAD

**Issue by saraminecraft** [P3pp3rF1y/AncientWarfare2#939]
Hi! <3 Amazing mod!!! In the drafting table only bridges are available for building. 

![image](https://user-images.githubusercontent.com/29168568/57000831-3fa51680-6b6a-11e9-9a51-16280d10bc1e.png)

Am I doing something wrong? Are there other structures available for survival mode? Let me know when you have the time if ok :)
Many Thanks! <3 Sara

**Comment by ThatPolishKid99** [comment]
Hi, this is intentional, these are structures set for survival building, the rest are not. When you scan your own structures, you can set them to survival building by checking the correct setting. 
Please join the Discord so you can ask questions before posting issues on GitHub
https://discord.gg/RC2PkXj
