### ISSUE TITLE
JEI deleting items

### ISSUE THREAD

**Issue by Exavator** [P3pp3rF1y/AncientWarfare2#956]
Whenever I attempt to quick select a recipe in the engineering station, if there are items already present in the crafting grid, they get deleted (I tested this with a vanilla crafting bench and the items went back into my inventory)

Here's the hastebin that VanillaFix generated
https://paste.dimdev.org/marucunufi.mccrash

**Comment by P3pp3rF1y** [comment]
I have fixed the part of the code that moves items from crafting grid back to inventory. But you also seem to have an issue with something else that conflicts with recipe lookup. It may be some specific recipe that doesn't work in this case or some mod that conflicts here. so after these changes you will see items properly into inventory but I am pretty sure you won't see crafting grid filled with items for the recipe you have selected. To know why that happens I would need to know what recipe this happens with and if it happens when just AW is included in the pack or with a specific mod in the pack (which is my guess is the case)

**Comment by Exavator** [comment]
I've noticed the issue while making Pam's chicken sandwiches, as it deleted my cookware, as well as the AW bounds upgrades deleting the fence/string, and the vanilla planks recipe

**Comment by Exavator** [comment]
I just tested it with just HWYLA, JEI, and AW. Everytime I autofilled a recipe ( I tested with sticks and large bounds upgrades) it deleted my items in the crafting grid

**Comment by WinDanesz** [comment]
Are you on the latest dev build?

**Comment by Exavator** [comment]
I'm not on the dev build, I'll try that now

**Comment by Exavator** [comment]
Yeah it autofills and replaces now. Thanks!
