### ISSUE TITLE
Combat NPC doesnt attack or take damage?

### ISSUE THREAD

**Issue by Zwasco** [P3pp3rF1y/AncientWarfare2#967]
i made a team by /scoreboard teams add.. and i fed the soldiers and gave them upkeep and combat orders but they dont take damage from enemies and from me, also they do not attack the enemies?     

 **This only happens in 1.12.2 version, not in 1.7.10**

**Comment by MohawkyMagoo** [comment]
This is due to the user having a pirated or cracked version of Minecraft / and or the T-Launcher.  This is not our problem and dont expect any sympathy. The NPCs take their hostility stance from the owner, and if the owner doesn’t have a UUID as pirated copies don’t, then they have no hostility to anything. So they won’t attack or be hurt by anything. This is not a bug, its not something we need to fix or worry about - buy a copy of the game cheapskate!

**Comment by Zwasco** [comment]
so why i got banned from discord? its because i have a cracked acc ?

**Comment by MohawkyMagoo** [comment]
Because you wouldnt take no for an answer - its not our problem to solve your problem when its caused by your own piracy of software.

**Comment by Zwasco** [comment]
yes ok forget about that but why i got banned from your discord, i like your mod even if i couldnt do what i want and there is 1.7.10 version so why i get ban for no reason, ok i dont want anyone to solve my problem just iam happy like this but i got banned from your mod's discord,  ???
