### ISSUE TITLE
Advanced loot chests are always empty

### ISSUE THREAD

**Issue by StraightBusta** [P3pp3rF1y/AncientWarfare2#981]
Confirmed this with a fresh install with only AW2 and cores installed, they were all still empty. Regular minecraft chests spawned in AW2 structures have loot as expected.

**Comment by P3pp3rF1y** [comment]
How do you actually recognize regular chests from AW2 ones? 
And which structures you are in where you don't see any loot? ("/awstructure name" in the structure)
We only spawn in randomized loot with AW2 ones and there will be empty chests all over the place because we only want smaller number of chests to have loot, the bigger the structure the more chests you will find with loot.

**Comment by StraightBusta** [comment]
Hwyla lets me see what I'm looking at. I made a new try today and actually found some loot in PirateIslandCastleOcean's advanced loot chests so there's that. I must've been very unlucky because me and my friend went through probably 10-15 chests and they were all empty.

However, when opening some of them I would get "[minecraft/LootTableManager]: Could'nt find resource table ebwizardry:subsets/wizard_armour" in the server log, is this intended? Could this have been the reason to why I couldn't find any loot?

**Comment by WinDanesz** [comment]
Do you have Electroblob's Wizardry in your modpack?

**Comment by WinDanesz** [comment]
If you join our Discord server, we can help with problems faster btw

**Comment by StraightBusta** [comment]
No I don't have that mod installed. Do chests have a set loot table for each structure? Do the chests not have a fallback loot table in case of a mod not being present? It's no big deal really, I'll just up the loot rate to make up for those who are missing a table and end up empty not just by chance.

**Comment by ThatPolishKid99** [comment]
No, there is no fallback loot table, but it is something we can consider. It's reccomenned to have all the supported mods listed in the #manual chat in the discord. Please feel free to ask more questions, but I'll close this issue for now

**Comment by Azriel-Legnasia** [comment]
An option to disable Loot Tables from mods one doesn't have would be nice as well.

**Comment by WinDanesz** [comment]
Doesn't really makes sense in this context since the loot tables are already assigned to each chests in a structure, in the schematic file. Can't disable something you don't have in your environment, it simply doesn't load the table if you dont have the provider mod.
This also is only slightly related to this closed issue. 
Feel free to join our Discord where we can discuss issues and suggestions more easily.
