### ISSUE TITLE
Crop Farm Failure with Reeds and Cactus

### ISSUE THREAD

**Issue by bombcat2015** [P3pp3rF1y/AncientWarfare2#986]
Crop farm does not harvest/plant Sugar Cane and Cactus correctly.  It just repeatedly digs up the sugar cane and cactus and replants immediately after tilling all soil in bounding box...very frustrating since the reed farm did it's job so well.  The fruit farm is great, and the wood farm works well...not sure why you did away with the reed farm.  The crop farm also removes all water blocks in bounding box.  Not sure what the fix is but it presently isn't working.

Great mod btw, I really love it...it adds a level of excitement and complexity I haven't found in other mods....however it is seriously lacking in current tutorials or wiki information....for being such an amazing mod it really is missing a ton of the stuff normal mods have that make them take off.

Thanks and I look forward to your fixes.

**Comment by WinDanesz** [comment]
Have you tried cacti and cane on sand?

**Comment by WinDanesz** [comment]
Also, for more info check the ingame manual Treatise on Principles of Ruling and our Discord channel and we also have an FAQ section here in the Github wiki.

**Comment by bombcat2015** [comment]
Yes both...it just tears them up and replants repeatedly...it doesn't allow them to grow whatsoever.....and it occupies the farmers in perpetuity.

________________________________

**Comment by bombcat2015** [comment]
Sorry Farmers, in perpetuity....for farms.

Sincerely,

Austin

________________________________

**Comment by bombcat2015** [comment]
I've read all the in game and online information...it's sorely outdated.  I did find a work around, though it won't plant anything....you set the farm 1 block above the ground....it will then clear anything above 2 blocks tall...won't plant anything but if you get it started it will do the rest.
________________________________

**Comment by ThatPolishKid99** [comment]
Hi, so to start, the in-game manual, Treatise on Principles of Ruling is up to date, so I'm not sure why you would consider it otherwise. 
Second, I have been testing it, and I cannot get the crop farm to do what you've been saying it does. 
The sugercane on grass is the only one i had some minor issue with, since it attempted to hoe the grass, but that can be avoided by planting the sugarcane manually, first, and it works after that, or simply planting it on sand. I encountered no issues with the cacti. 
I am including a screenshot of my setup so you can compare. 
![2019-07-15_15 15 53](https://user-images.githubusercontent.com/10103417/61246189-e170e400-a713-11e9-9fa5-3139891ea4e0.png)
